### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by marcelowu** [troublediehard/magento-react-native#10]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.676 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
![screenshot_20180813-043027](https://user-images.githubusercontent.com/30912144/44019608-ae7efa6c-9eb5-11e8-9dc1-12629ca43824.jpg)

**Comment by troublediehard** [comment]
It doesn't look like something related to the project itself, but something with android run with react native. Please have look following https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

**Comment by marcelowu** [comment]
I tested it on another cell phone, and showed it.

Installing APK 'app-debug.apk' on 'Moto G Play - 7.1.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL
![default](https://user-images.githubusercontent.com/30912144/44070317-811ebac2-9f59-11e8-8764-dd3084e5f54d.PNG)

**Comment by troublediehard** [comment]
@marcelowu did you try the solution from the screenshot you attached?

**Comment by marcelowu** [comment]
same thing,  I solved with ubuntu, error windows 7...

**Comment by marcelowu** [comment]
stripe or paypal future?

**Comment by troublediehard** [comment]
@marcelowu regarding this thread https://github.com/facebook/react-native/issues/14209 there is some issue with react-native 0.56 on windows, so possible solution is a downgrade to 0.55.4.


`stripe or paypal future?`
I think about payment implementation but in most cases it specific to the store. Probably, I'll add PayPal since it exists by default in Magento.
