### ISSUE TITLE
About Magento react native app Home page

### ISSUE THREAD

**Issue by Damithdrg** [troublediehard/magento-react-native#102]
Hi, I'm new to magento and react native, I'm up magento 2.2 server and Run this app on android but in app magento home page not shoving and other view are working perfectly. 
please guide me how to config the magento sever or app to show the mobile home page,.

thank you . 

  
![Untitled](https://user-images.githubusercontent.com/17777620/69401147-453a9780-0d1a-11ea-93d0-14eb06d1e405.jpg)
![Untitled1](https://user-images.githubusercontent.com/17777620/69401148-45d32e00-0d1a-11ea-9253-349d36c45c1d.jpg)

**Comment by alexakasanjeev** [comment]
@Damithdrg Did you follow the instructions mentioned in here
https://github.com/troublediehard/magento-react-native/wiki/Setup
> Setup new CMS block in Magento Admin which will be used in HomePage

**Comment by Damithdrg** [comment]
thank you alexakasanjeev , but my issue is same i'm follow the setup on    https://github.com/troublediehard/magento-react-native/wiki/Setup
. 
my cms_block_config.json lock like this

{
  "slider": [
    {
      "title": "New Luma Yoga Collection",
      "image": "wysiwyg/home/home-main.jpg"
    },
    {
      "title": "Even more ways to mix and match",
      "image": "wysiwyg/home/home-t-shirts.png"
    },
    {
      "title": "Find conscientious, comfy clothing in our eco-friendly collection",
      "image": "wysiwyg/home/home-eco.jpg"
    }
  ],
  "featuredCategories": {
    "3": { "title": "Electronic"},
    "4": { "title": "Home & Furniture"}
  }
}

the Categories are that i created but i couldn't create slider because i dont now how to create slider in magento server .

is that important  to view mobile home page, if is it please tell me how to config slider in magento

thank you

**Comment by troublediehard** [comment]
@Damithdrg please share screenshot of your cms block in Magento admin panel.

**Comment by Damithdrg** [comment]
thenk you troublediehard,

these are my cms block in Magento admin panel screenshot 
![Untitled2](https://user-images.githubusercontent.com/17777620/69405239-27266480-0d25-11ea-84e8-4403a92b473a.jpg)
![Untitled3](https://user-images.githubusercontent.com/17777620/69405240-27266480-0d25-11ea-8a96-b4741c065d31.jpg)

thank you

**Comment by troublediehard** [comment]
You have to add correct file paths for your  slider images.

1. Press `Show / Hide Editor` <img width="185" alt="Screen Shot 2019-11-22 at 9 45 03 AM" src="https://user-images.githubusercontent.com/6594232/69407360-ff2b0700-0d0c-11ea-9dae-63bacaa15dd4.png">

2. Press `Insert Image...` <img width="598" alt="Screen Shot 2019-11-22 at 9 45 14 AM" src="https://user-images.githubusercontent.com/6594232/69407397-0ce08c80-0d0d-11ea-9960-4fe0db29d3a5.png">

3. <img width="562" alt="Screen Shot 2019-11-22 at 9 45 28 AM" src="https://user-images.githubusercontent.com/6594232/69407439-22ee4d00-0d0d-11ea-8e18-c4f483f76305.png">

Here you can see all images stored in `wysiwyg` directory.

**Comment by Damithdrg** [comment]
Thank You @troublediehard ,

Did I have to add my all image math to  cms_block_config.json file

**Comment by troublediehard** [comment]
`cms_block_config.json` is just a configuration sample, it doesn't do anything.

**Comment by alexakasanjeev** [comment]
> thank you alexakasanjeev , but my issue is same i'm follow the setup on https://github.com/troublediehard/magento-react-native/wiki/Setup
> .
> my cms_block_config.json lock like this
> 
> {
> "slider": [
> {
> "title": "New Luma Yoga Collection",
> "image": "wysiwyg/home/home-main.jpg"
> },
> {
> "title": "Even more ways to mix and match",
> "image": "wysiwyg/home/home-t-shirts.png"
> },
> {
> "title": "Find conscientious, comfy clothing in our eco-friendly collection",
> "image": "wysiwyg/home/home-eco.jpg"
> }
> ],
> "featuredCategories": {
> "3": { "title": "Electronic"},
> "4": { "title": "Home & Furniture"}
> }
> }
> 
> the Categories are that i created but i couldn't create slider because i dont now how to create slider in magento server .
> 
> is that important to view mobile home page, if is it please tell me how to config slider in magento
> 
> thank you

The slider is actually pretty easy, you don't have to do anything special, the slider is just a json array that contains links to images which has been uploaded in magento.

1. goto `content > Block` in magento admin
2. Open the block you just created in edit mode
3. Click on `Show/Hide Editor` button
4. Click on `Insert Image` button
![insert_image(1)](https://user-images.githubusercontent.com/13250741/69407703-2db7da80-0d2b-11ea-86d4-e71652e39388.png)
5. Upload an image by clicking on `browse` button
![browse_image(1)](https://user-images.githubusercontent.com/13250741/69407851-85564600-0d2b-11ea-8db5-aa02841b5aab.png)
6. Click on the image and click on `insert file` button
![insert_img(1)](https://user-images.githubusercontent.com/13250741/69407941-be8eb600-0d2b-11ea-9d8d-ca3762644ee8.png)
7. Copy the image link  and paste it into slider array and remove the img tag
`<img src="{{media url="wysiwyg/new_home_page.png"}}" alt="" />`

**Comment by troublediehard** [comment]
@alexakasanjeev this is a great explanation! Can you also add it to the setup doc?

**Comment by alexakasanjeev** [comment]
sure :smile:

**Comment by alexakasanjeev** [comment]
done, created new page and added link in Setup guide

**Comment by Damithdrg** [comment]
Thank you @alexakasanjeev and @troublediehard ,

I config as u shown in configuration , but issue is same as before.


{
    "slider": [
      {
        "title": "New Luma Yoga Collection",
        "image": "wysiwyg/home-white-slider-2.jpg"
      },
      {
        "title": "Even more ways to mix and match",
        "image": "wysiwyg/home/1.jpg"
      },
      {
        "title": "Find conscientious, comfy clothing in our eco-friendly collection",
        "image": "wysiwyg/home-white-slider-2.jpg"
      },
      {"image":"wysiwyg/electronic/photo-1413708617479-50918bc877eb.png"},
  {"image":"wysiwyg/electronic/photo-1413708617479-50918bc877eb.png"},
  {"image":"wysiwyg/electronic/photo-1529611934128-376c7bb1c88a.jpg"}
  
    ],
    "featuredCategories": {
      "3": { "title": "Electronic"},
      "4": { "title": "Home & Furniture"}
    }
  }
  
my magento vertion is 2.3.2 is that a issue .

thank you

**Comment by alexakasanjeev** [comment]
try this
```json
{
  "slider": [
    {
      "title": "New Luma Yoga Collection",
      "image": "wysiwyg/electronic/photo-1413708617479-50918bc877eb.png"
    },
    {
      "title": "Even more ways to mix and match",
      "image": "wysiwyg/electronic/photo-1413708617479-50918bc877eb.png"
    },
    {
      "title": "Find conscientious, comfy clothing in our eco-friendly collection",
      "image": "wysiwyg/electronic/photo-1529611934128-376c7bb1c88a.jpg"
    },
  ],
  "featuredCategories": {
    "3": { "title": "Electronic"},
    "4": { "title": "Home & Furniture"}
  }
}
```

**Comment by Damithdrg** [comment]
Thank you @alexakasanjeev 

I try it to , but issue is same, is there any setting in magento for mobile home page view,  

thank you.

**Comment by alexakasanjeev** [comment]
did you set the block id that you created in magento.js file 
you need to set the block id in which you pasted that json to `home_cms_block_id`

```javascript
export const magentoOptions = {
  url: 'http://13.233.82.59/magento/index.php/',
  home_cms_block_id: 19,// required int
  authentication: {
    integration: {
      access_token: 'f6a7lmt61uyy2elepkvbwp4q0904beh5',
    },
  },
};
```

does your HomePage render anything?

**Comment by Damithdrg** [comment]
thank You @alexakasanjeev and @troublediehard ,

the issue is now fixed thank you guys so much , 

{
  "slider": [
    {
      "title": "New Luma Yoga Collection",
      "image": "wysiwyg/electronic/photo-1413708617479-50918bc877eb.png"
    },
    {
      "title": "Even more ways to mix and match",
      "image": "wysiwyg/electronic/photo-1413708617479-50918bc877eb.png"
    },
    {
      "title": "Find conscientious, comfy clothing in our eco-friendly collection",
      "image": "wysiwyg/electronic/photo-1529611934128-376c7bb1c88a.jpg"
    }
  ],
  "featuredCategories": {
    "3": { "title": "Electronic"},
    "4": { "title": "Home & Furniture"}
  }
}
