### ISSUE TITLE
Error: JSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by sid-metiz** [troublediehard/magento-react-native#104]
I Change Base Url and Change token And run the app.. Its giving me Error like

 [SyntaxError: JSON Parse error: Unrecognized token '<']
 LOG  [Error: JSON Parse error: Unrecognized token '<']
![device-2019-12-04-125448](https://user-images.githubusercontent.com/43472674/70121775-54fc9900-1695-11ea-88d2-4f15209896f9.png)
![device-2019-12-04-125541](https://user-images.githubusercontent.com/43472674/70121832-6645a580-1695-11ea-9154-bcfad633e394.png)

**Comment by alexakasanjeev** [comment]
Hi sid-metiz, could you share your base url and access token here or privately on sanjeevy133@protonmail.om, don't worry you can always delete the integration token

**Comment by sid-metiz** [comment]
> Hi sid-metiz, could you share your base url and access token here or privately on [sanjeevy133@protonmail.om](mailto:sanjeevy133@protonmail.om), don't worry you can always delete the integration token

its .om or .com?

**Comment by troublediehard** [comment]
@sid-metiz 
make sure you have a trailing slash for your 'url' in config like `https://my.magento.site.com/`, also try to add `store: ''` in your config like
```
export const magentoOptions = {
  url:"https://my.magento.com/",
  home_cms_block_id:"58",
  store: '',
  authentication:{integration:{access_token:"zttcv4znha3xizgpjgchwccf6nmvpsec"}}
}
```

**Comment by sid-metiz** [comment]
what i have to pass in store?? 04.12.2019, 14:59, "Dmytro Portenko" <notifications@github.com>:@sid-metiz
make sure you have a trailing slash for your 'url' in config like https://my.magento.site.com/, also try to add store: '' in your config like
export const magentoOptions = {
  url:"https://my.magento.com/",
  home_cms_block_id:"58",
  store: '',
  authentication:{integration:{access_token:"zttcv4znha3xizgpjgchwccf6nmvpsec"}}
}

**Comment by troublediehard** [comment]
try empty, as I mentioned above.

**Comment by sid-metiz** [comment]
ok but in home screen its dosent show any things04.12.2019, 15:10, "Dmytro Portenko" <notifications@github.com>:try empty, as I mentioned above.

**Comment by troublediehard** [comment]
any errors?

**Comment by sid-metiz** [comment]
No just blank Ui04.12.2019, 15:13, "Dmytro Portenko" <notifications@github.com>:any errors?

**Comment by troublediehard** [comment]
Try reinstall the app after config updated.

Actually you have to put in `store` store code from magento admin 
<img width="357" alt="Screenshot 2019-12-04 at 11 41 24" src="https://user-images.githubusercontent.com/6594232/70131743-82444980-168b-11ea-9677-d801d9db0183.png">
<img width="175" alt="Screenshot 2019-12-04 at 11 43 02" src="https://user-images.githubusercontent.com/6594232/70131753-85d7d080-168b-11ea-98d7-279b6a450cf4.png">

**Comment by sid-metiz** [comment]
Can its show price as per Customer Group?04.12.2019, 15:13, "Dmytro Portenko" <notifications@github.com>:any errors?

**Comment by troublediehard** [comment]
It is not implemented in the app to `show price as per Customer Group`

**Comment by sid-metiz** [comment]
04.12.2019, 15:16, "Dmytro Portenko" <notifications@github.com>:Try reinstall the app after config updated.
Actually you have to put in store store code from magento admin

**Comment by sid-metiz** [comment]
I put english in Store variable but still having issue04.12.2019, 15:17, "Dmytro Portenko" <notifications@github.com>:It is not implemented in the app to show price as per Customer Group

**Comment by troublediehard** [comment]
please join Slack for further discussion https://join.slack.com/t/magento-react-native/shared_invite/enQtNjE3ODY0MDUxOTQyLTgwNDY2YzczNTEyNjQyY2QzMmY5ZDY4MmZlYjMyYmRiYzgzZjBiMDhmOTYxMDZkZjAwODkwZGI2MjAxY2FkNTE

**Comment by Digiraf** [comment]
i had the same problem with the create  customer request. check your request output en debug it.
magento 3.5 en 2.2.4 api differs so test you Api with swagger. if it works check the request url and compare it with what the app calls. i found out in my case that the store code in Magento\Store\Model\StoreRepository.php that the $code = 'rest' instead of the code in the request url.
i overrided Magento\Store\Model\StoreRepository.php with a small adjustment:

`....
    public function get($code)
    {
        if($code=='rest'){
            $code='default';
        }`

**Comment by dimaportenko** [comment]
Hi @Digiraf,
Sorry, I don't understand what you described above. 
 
 1. what do you mean by `create customer request` ?
 2. what is `magento 3.5`, as I know latest version of magento 2.4.x ?

**Comment by Digiraf** [comment]
1- the POST request to create customer with the API: V1/customers
2-  magento 2.3.5-p1 version

I tested it with both versions and the rest API is apparently different in Magento latest version.

when i test the request with swagger: `swagger#/customerAccountManagementV1/customerAccountManagementV1CreateAccountPost` 
it returns: `/default/rest/all/V1/customers ` as request url.
But the app is doing `/rest/default/V1/customers` this causes  an empty output. after debug ` Magento\Store\Model\StoreRepository.php ` in the get function the store code is wrong it should be default but it is coming as 'rest'.

**Comment by dimaportenko** [comment]
I don't know if Magento changed the rest endpoint structure since I've started this project, but randomly opened docs stills points to the 
```
<HTTP verb> http://<host>/rest/<scope>/<endpoint>
```

https://devdocs.magento.com/guides/v2.4/rest/tutorials/index.html#performing-steps

@Digiraf are you testing with a clean Magento version or you have 3d party extension or some customization?

**Comment by dimaportenko** [comment]
Also, I've just checked swagger on clean Magento 2.4, it shows
```
https://magentodev.local/index.php/rest/all/V1/customers
```
so it's still the same.

**Comment by dimaportenko** [comment]
Take a look https://magento.stackexchange.com/questions/216476/magento-2-api-default-vs-all-vs-none

so `all` and `default` are scope variables and you have it twice in your endpoint `/default/rest/all/V1/customers`. Looks like definitely something was changed on your Magento instance and it's not working as initially designed.

**Comment by Digiraf** [comment]
> Also, I've just checked swagger on clean Magento 2.4, it shows
> 
> ```
> https://magentodev.local/index.php/rest/all/V1/customers
> ```
> 
> so it's still the same.

Have you tested it in 2.3.5-p1?

**Comment by Digiraf** [comment]
> Take a look https://magento.stackexchange.com/questions/216476/magento-2-api-default-vs-all-vs-none
> 
> so `all` and `default` are scope variables and you have it twice in your endpoint `/default/rest/all/V1/customers`. Looks like definitely something was changed on your Magento instance and it's not working as initially designed.

I think that is a quick conclusion don't you think? You didn't tested it in 2.3.5-p1?

Besides i have a lot of things to notice in your app and i was shocked that you are using admin endpoints from within the customer app. Request like sales orders  

Try your self to test as folows:

1-create account in the app
2-add something in cart
3-logout
4-try to add something in the cart. That will fail
5-Login
6-add to cart. That will fail

I had to rewrite the hole src/magento/index.js and none of the requests are admin.

I had to also create new webapi endpoints to achieve what i wanted. but thanks for looking up anyway i solved my problem

**Comment by dimaportenko** [comment]
> @Digiraf are you testing with a clean Magento version or you have 3d party extension or some customization?

**Comment by dimaportenko** [comment]
> i was shocked that you are using admin endpoints
I think you overrate `admin` endpoints. It just means the endpoint requires additional permissions. 

Generally, Magento 2 out-of-box REST API is awful and I don't recommend using it if you are going to build a solid solution. 

Luckily, Magento team introduce GraphQL. For those, who are curious about usage of Magento 2 GraphQL API I recommend to check https://github.com/dimaportenko/magento-react-native-community

**Comment by dimaportenko** [comment]
> I think that is a quick conclusion don't you think? You didn't tested it in 2.3.5-p1? and as i mentioned both versions behaves very different with the rest API

My quick conclusion is based on years of experience work with Magento. I can bet 100$ I'm correct. @Digiraf let me know if you're in.

**Comment by Digiraf** [comment]
> > I think that is a quick conclusion don't you think? You didn't tested it in 2.3.5-p1? and as i mentioned both versions behaves very different with the rest API
> 
> My quick conclusion is based on years of work experience with Magento. I can bet 100$ I'm correct. @Digiraf let me know if you're in 😉

Am sure about your experience. Am not sure about magento2.
You made a lot of effort in the app and thats a great work but after tests i see that it fails to refresh quote ids or tokens  for both cusomer and guests. that is very frustrating. but again i have fixed it

**Comment by Digiraf** [comment]
post request like these an easily be be changed to a different customer. so if you call this in every app you are selling a hug security issue for all merchants

**Comment by dimaportenko** [comment]
> i have fixed it

I don't see your PRs

> so if you call this in every app you are selling

I'm not selling anything and as I said above I don't recommend use Magento REST API for mobile app at all (since GraphQL exists). 

> i was shocked
>  that is very frustrating

Btw I'm also shocked you are using this app. And I'm very frustrated you didn't pick another well done alternatives, or even better create it yourself.

**Comment by Digiraf** [comment]
> > i have fixed it
> 
> I don't see your PRs
> 
> > so if you call this in every app you are selling
> 
> I'm not selling anything and as I said above I don't recommend use Magento REST API for mobile app at all (since GraphQL exists).
> 
> > i was shocked
> > that is very frustrating
> 
> Btw I'm also shocked you are using this app. And I'm very frustrated you didn't pick another well done alternatives, or even better create it yourself.

i write all apps you want native or anything else and i promise you i've seen many better alternatives.
but again thanks for waste of time.
