### ISSUE TITLE
Price not show as per customer group..

### ISSUE THREAD

**Issue by sid-metiz** [troublediehard/magento-react-native#106]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.
Hii Price not show as there is a multipal group of customer. all have different price

**Comment by troublediehard** [comment]
@sid-metiz please provide step by step instructions on how to set up and test it on the Magento side.

**Comment by sid-metiz** [comment]
i have four group in customer and all have different price assign.. So its come from array of tier_price

**Comment by sid-metiz** [comment]
![Screenshot from 2019-12-04 17-33-14](https://user-images.githubusercontent.com/43472674/70141059-2e9e2400-16bc-11ea-8b3e-d674b2c09d7a.png)

**Comment by sid-metiz** [comment]
Hello

**Comment by troublediehard** [comment]
@sid-metiz please provide step by step instructions on how to set up and test it on the Magento side.  Here is the sample of good step by step instruction https://github.com/troublediehard/magento-react-native/wiki/Setup

**Comment by sid-metiz** [comment]
@troublediehard  I have Customer group in Customer, Where there is a different type of customer as per role. so there is a tier_prices list (array) come in Api. Which give price as per role..
i want a price as per the role..

**Comment by troublediehard** [comment]
@sid-metiz you marked an issue as a question. So what is your question actually is?

**Comment by sid-metiz** [comment]
@troublediehard  if i login as a super user so can the price is visible for me that is assign to the super user?

**Comment by troublediehard** [comment]
@sid-metiz, as I've already told you such functionality isn't implemented in this project.

**Comment by sid-metiz** [comment]
Ok will you implement or not?04.12.2019, 19:46, "Dmytro Portenko" <notifications@github.com>:@sid-metiz, as I've already told you such functionality isn't implemented in this project.

**Comment by troublediehard** [comment]
Probably at some point, but it is surely not in priority for the near future.

**Comment by sid-metiz** [comment]
Ok thanks.. I want that feature...
