### ISSUE TITLE
Razorpay not implement

### ISSUE THREAD

**Issue by sid-metiz** [troublediehard/magento-react-native#107]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.
Hii where is rozarpay implement?

**Comment by troublediehard** [comment]
rozarpay is not implemented

**Comment by sid-metiz** [comment]
ok i know how to implement but where i should put that method?

**Comment by troublediehard** [comment]
`src/components/checkout/CheckoutPaymentMethod.js` good place to start

**Comment by sid-metiz** [comment]
Ok thanks04.12.2019, 19:31, "Dmytro Portenko" <notifications@github.com>:src/components/checkout/CheckoutPaymentMethod.js good place to start
