### ISSUE TITLE
Cart Item Price show 0

### ISSUE THREAD

**Issue by sid-metiz** [troublediehard/magento-react-native#108]
**Describe the bug**

**Expected behavior**

**Current Behavior**
What is the current behavior?

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Navigate to...
2. Press on...
3. Scroll to...
4. See error...

**Screenshots**

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.1.0]

**Additional context**

**Comment by alexakasanjeev** [comment]
@sid-metiz could you see issue #77 and if it is same, you can close this one, if your problem is different please provide more information

**Comment by troublediehard** [comment]
duplicate https://github.com/troublediehard/magento-react-native/issues/77

**Comment by sid-metiz** [comment]
When Add to cart Product price show 0

**Comment by alexakasanjeev** [comment]
Add two product to the cart, and see if price is still zero.

**Comment by sid-metiz** [comment]
if only one item in cart

**Comment by alexakasanjeev** [comment]
Yes if there is one item in cart, price is zero, we know this problem, and it is mentioned in issue #77

**Comment by sid-metiz** [comment]
Ok thanks..
