### ISSUE TITLE
How to Add Simple Product with Color Selection in Cart(Can you give me a Example or A Payload)

### ISSUE THREAD

**Issue by sid-metiz** [troublediehard/magento-react-native#110]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.
{
  "id": 385,
  "sku": "PS-07",
  "name": "ROUND INSERT CHANGEABLE PEN HOLDER ",
  "attribute_set_id": 4,
  "price": 100,
  "status": 1,
  "visibility": 4,
  "type_id": "simple",
  "created_at": "2019-09-30 07:00:52",
  "updated_at": "2019-11-29 10:12:24",
  "extension_attributes": {
    "website_ids": [
      1
    ],
    "category_links": [
      {
        "position": 0,
        "category_id": "29"
      },
      {
        "position": 0,
        "category_id": "60"
      },
      {
        "position": 0,
        "category_id": "62"
      },
      {
        "position": 0,
        "category_id": "70"
      },
      {
        "position": 0,
        "category_id": "69"
      }
    ]
  },
  "product_links": [
    
  ],
  "options": [
    {
      "product_sku": "PS-07",
      "option_id": 97,
      "title": "Select Colour",
      "type": "checkbox",
      "sort_order": 1,
      "is_require": true,
      "max_characters": 0,
      "image_size_x": 0,
      "image_size_y": 0,
      "values": [
        {
          "title": "Green",
          "sort_order": 1,
          "price": 0,
          "price_type": "fixed",
          "option_type_id": 328
        },
        {
          "title": "Blue",
          "sort_order": 2,
          "price": 0,
          "price_type": "fixed",
          "option_type_id": 329
        },
        {
          "title": "Yellow",
          "sort_order": 3,
          "price": 0,
          "price_type": "fixed",
          "option_type_id": 330
        },
        {
          "title": "Pink",
          "sort_order": 4,
          "price": 0,
          "price_type": "fixed",
          "option_type_id": 331
        }
      ]
    }
  ],
  "media_gallery_entries": [
    {
      "id": 639,
      "media_type": "image",
      "label": null,
      "position": 2,
      "disabled": false,
      "types": [
        "image",
        "small_image",
        "thumbnail",
        "swatch_image"
      ],
      "file": "/p/s/ps-07-3007-kq269.jpg"
    },
    {
      "id": 1154,
      "media_type": "image",
      "label": null,
      "position": 3,
      "disabled": false,
      "types": [
        
      ],
      "file": "/p/s/ps-07-photo_frame_2_.jpg"
    },
    {
      "id": 1155,
      "media_type": "image",
      "label": null,
      "position": 4,
      "disabled": false,
      "types": [
        
      ],
      "file": "/p/s/ps-07-photo_frame_3_.jpg"
    },
    {
      "id": 1156,
      "media_type": "image",
      "label": null,
      "position": 5,
      "disabled": false,
      "types": [
        
      ],
      "file": "/p/s/ps-07-photo_frame_4_.jpg"
    }
  ],
  "tier_prices": [
    {
      "customer_group_id": 2,
      "qty": 1,
      "value": 40,
      "extension_attributes": {
        "website_id": 0
      }
    },
    {
      "customer_group_id": 3,
      "qty": 1,
      "value": 50,
      "extension_attributes": {
        "website_id": 0
      }
    },
    {
      "customer_group_id": 4,
      "qty": 1,
      "value": 40,
      "extension_attributes": {
        "website_id": 0
      }
    },
    {
      "customer_group_id": 5,
      "qty": 1,
      "value": 50,
      "extension_attributes": {
        "website_id": 0
      }
    }
  ],
  "custom_attributes": [
    {
      "attribute_code": "image",
      "value": "/p/s/ps-07-3007-kq269.jpg"
    },
    {
      "attribute_code": "url_key",
      "value": "insert-changeable-pen-holder"
    },
    {
      "attribute_code": "special_price",
      "value": "50.0000"
    },
    {
      "attribute_code": "gift_message_available",
      "value": "2"
    },
    {
      "attribute_code": "small_image",
      "value": "/p/s/ps-07-3007-kq269.jpg"
    },
    {
      "attribute_code": "meta_title",
      "value": "INSERT CHANGEABLE PEN HOLDER "
    },
    {
      "attribute_code": "special_from_date",
      "value": "2019-09-30 00:00:00"
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "thumbnail",
      "value": "/p/s/ps-07-3007-kq269.jpg"
    },
    {
      "attribute_code": "meta_keyword",
      "value": "INSERT CHANGEABLE PEN HOLDER "
    },
    {
      "attribute_code": "hsn_code",
      "value": "9608"
    },
    {
      "attribute_code": "swatch_image",
      "value": "/p/s/ps-07-3007-kq269.jpg"
    },
    {
      "attribute_code": "meta_description",
      "value": "INSERT CHANGEABLE PEN HOLDER  "
    },
    {
      "attribute_code": "size_cms",
      "value": "8 x 8 x 12.5"
    },
    {
      "attribute_code": "tax_class_id",
      "value": "12"
    },
    {
      "attribute_code": "required_options",
      "value": "1"
    },
    {
      "attribute_code": "has_options",
      "value": "1"
    },
    {
      "attribute_code": "category_ids",
      "value": [
        "29",
        "60",
        "62",
        "70",
        "69"
      ]
    },
    {
      "attribute_code": "sw_featured",
      "value": "0"
    },
    {
      "attribute_code": "product_page_type",
      "value": "default"
    },
    {
      "attribute_code": "product_image_size",
      "value": "0"
    }
  ]
}

This is my Responce of Product

**Comment by troublediehard** [comment]
It is implemented in the app. And you can see the request in logs.
