### ISSUE TITLE
What should we access ?

### ISSUE THREAD

**Issue by Md-Asaduzzaman-Muhid** [troublediehard/magento-react-native#113]
if we  allow all resources for the access token. may have security risk. so ,
what is necessary and must select to run this app properly.

**Comment by troublediehard** [comment]
@Md-Asaduzzaman-Muhid I don't have an exact list right now. You can find all rest API endpoints which use access token in `src/magento/lib/admin/index.js`.  

Then you can open Magento source and search for webapi.xml file somewhere in vendor/magento directory and find what resource it requires.

For example `GET /V1/store/storeConfigs` is defined in `vendor/magento/module-store/etc/webapi.xml` 
```
<!-- Store Config -->
<route url="/V1/store/storeConfigs" method="GET">
    <service class="Magento\Store\Api\StoreConfigManagerInterface" method="getStoreConfigs"/>
    <resources>
        <resource ref="Magento_Backend::store"/>
    </resources>
</route>
```

So the required resource for this particular endpoint is `Magento_Backend::store`.

In case you are going to collect all the required resources please share it here then I'll add it to the docs.

**Comment by Md-Asaduzzaman-Muhid** [comment]
Thank you so much for your quick response.
