### ISSUE TITLE
in product details cart reset

### ISSUE THREAD

**Issue by Md-Asaduzzaman-Muhid** [troublediehard/magento-react-native#114]
Hi,

When i go into a products detail page it reset the cart value to 0 .

**Comment by troublediehard** [comment]
@Md-Asaduzzaman-Muhid can you please remove the app, install it again and record video with bug reproduction?

**Comment by troublediehard** [comment]
@Md-Asaduzzaman-Muhid also, could it be the same issue as described in https://github.com/troublediehard/magento-react-native/issues/77 ?

**Comment by Md-Asaduzzaman-Muhid** [comment]
@troublediehard no they are not same ... once i got it worked fine but today i found this issue . i am sending a video link please see and if you give suggestion what file should have cart functionality and why in product details page cart rest it would be greatful

Thanks for your quick response.

**Comment by Md-Asaduzzaman-Muhid** [comment]
https://drive.google.com/file/d/1xXJd21jvKvtidWKy8zEqxXiy8G6sFuRQ/view?usp=drivesdk
here is the video url from my google drive .. please take a look

**Comment by troublediehard** [comment]
@Md-Asaduzzaman-Muhid 
I tried to reproduce it on my end but no luck
1. Have you done any changes to the codebase? 
2. It is possible problem relates to your Magento setup, so if you don't mind to share your config file I can try it on my end (you can send it to the email troublesohard@gmail.com or join to Slack workspace https://join.slack.com/t/magento-react-native/shared_invite/enQtNjE3ODY0MDUxOTQyLTgwNDY2YzczNTEyNjQyY2QzMmY5ZDY4MmZlYjMyYmRiYzgzZjBiMDhmOTYxMDZkZjAwODkwZGI2MjAxY2FkNTE )

**Comment by Md-Asaduzzaman-Muhid** [comment]
@troublediehard 
1. No i don't change any code.
2. I setup magento and never change anything in code just add mmobile home page and your provided schema.
3. "warning viewpagerandroid has been extracted from react-native core " this message shown when i enable yellow box.

I have sent you config file in email please take a look

Thank you

**Comment by troublediehard** [comment]
There is no way to investigate the issue without more information or a test environment where the issue can be reproduced. 

Please provide chrome console output in with enabled debugger.
