### ISSUE TITLE
on productlist grid icon on header just work once it  do not toggle 

### ISSUE THREAD

**Issue by zeeshoe** [troublediehard/magento-react-native#115]
on productlist grid icon on header just work once it  do not toggle

**Comment by troublediehard** [comment]
@zeeshoe fixed, feel free to take a look.

**Comment by zeeshoe** [comment]
![Screenshot_1579100622](https://user-images.githubusercontent.com/59910489/72444734-64155180-37d2-11ea-9539-acdd00114dfb.png)
Got this after solution.

**Comment by troublediehard** [comment]
@zeeshoe It doesn't look like it relates to my changes. Also, works fine on both iOS and Android. Please let me know if you have any specific steps to reproduce. 

<img width="589" alt="Screenshot 2020-01-15 at 18 10 26" src="https://user-images.githubusercontent.com/6594232/72450170-91f29a00-37c2-11ea-9a2b-a29008b06e19.png">

**Comment by troublediehard** [comment]
also, you can have a look if there any other errors in chrome devtools console https://facebook.github.io/react-native/docs/debugging
