### ISSUE TITLE
Not Install

### ISSUE THREAD

**Issue by lanvo21** [troublediehard/magento-react-native#117]
Run: npm install error
![image](https://user-images.githubusercontent.com/60998321/74402225-2f8ac900-4e56-11ea-940e-08f9c2d5e1de.png)

Please check and can guide how to solve it.

Thanks.

**Comment by troublediehard** [comment]
I don't have this issue on my end. Try following https://stackoverflow.com/questions/60172598/not-able-to-install-npm-install-react-native-gesture-handler

**Comment by troublediehard** [comment]
@lanvo21 feel free to reopen this issue if you want to continue discussing
