### ISSUE TITLE
Hide slider if slider.length < 1

### ISSUE THREAD

**Issue by tylerssn** [troublediehard/magento-react-native#118]
**Describe the bug**
An error is thrown when an empty array is provided to the slider object.

**Expected behavior**
Slider should be hidden

**Current Behavior**
Error is thrown

**Steps to Reproduce**
Create the homepage block of:

```json
{
  "slider": [
  ],
  "featuredCategories": {
    "15": { "title": "Products"},
    "12": { "title": "Recipes"}
  }
}
```

OR

```json
{
  "featuredCategories": {
    "15": { "title": "Products"},
    "12": { "title": "Recipes"}
  }
}
```

**Comment by troublediehard** [comment]
Can you share the error?

**Comment by troublediehard** [comment]
I don't see any issues related to the config you provided.

I recommend you to purge store data in case you had the wrong config and it was saved on the device. To do it go to the `src/store/index.js` and uncomment `persistor.purge();` line.

**Comment by tylerssn** [comment]
I apologise for the lack of detail. I'm going to close this out since I can't provide further information at this time.

**Comment by troublediehard** [comment]
no problem
