### ISSUE TITLE
I run "npm install" get down Notice . 

### ISSUE THREAD

**Issue by 234146326** [troublediehard/magento-react-native#119]
![image](https://user-images.githubusercontent.com/17285770/75411460-44895100-595a-11ea-84c9-528966916cb4.png)

I'm not sure if I want to use the command(  `npm audit fix` ) and fix it.Have you encountered it?

**Comment by troublediehard** [comment]
I'm using yarn, and there is no `yarn audit fix`, so I'm not going to do anything with it right now. https://github.com/yarnpkg/yarn/issues/7075
But feel free to do it on your end.
