### ISSUE TITLE
Home page sliders image not show and featuredCategories products not showing 

### ISSUE THREAD

**Issue by samsonegba** [troublediehard/magento-react-native#120]
**Describe the bug**
Hello, I am new to Magento and React Native as well, I followed the instructions and compiled the app, installed Magento and everything works fine except for the home page. 
The homepage displays the slider's caption but not the image itself, I have tried and restarted the app and local server many times, every other pages works fine, but the homepage doesn't.

**Expected behavior**
I expected the homepage block to display with image as I carefully uploaded the image in path "wysiwyg/home/"and copied the image path to the slider->image JSON param

**Screenshots**
![Screenshot 2020-02-27 at 4 31 33 PM](https://user-images.githubusercontent.com/61153805/75459065-1ec27300-597f-11ea-8439-c0100124f45d.png)
![Screenshot 2020-02-27 at 4 33 42 PM](https://user-images.githubusercontent.com/61153805/75459068-208c3680-597f-11ea-8e1b-0f80a0d17acd.png)
![Screenshot 2020-02-27 at 4 34 55 PM](https://user-images.githubusercontent.com/61153805/75459070-208c3680-597f-11ea-8ea1-142c42d98f51.png)

**Additional context**

**Comment by troublediehard** [comment]
@samsonegba can you share your cms block config here?

**Comment by samsonegba** [comment]
Okay its just as the basic structure you provided

{
  "slider": [
    {
      "title": "New Luma Yoga Collection",
      "image": "wysiwyg/home/slide1.jpg"
    },
    {
      "title": "Even more ways to mix and match",
      "image": "wysiwyg/home/slide2.jpg"
    },
    {
      "title": "Find conscientious, comfy clothing in our eco-friendly collection",
      "image": "wysiwyg/home/slide3.jpg"
    }
  ],
  "featuredCategories": {
    "42": {
      "title": "Woman Sales"
    },
    "41": {
      "title": "Man Sales"
    }
  }
}

![Screenshot 2020-02-28 at 11 06 21 AM](https://user-images.githubusercontent.com/61153805/75539374-6c3fee00-5a1a-11ea-890e-52f5b0b6b9a5.png)

**Comment by troublediehard** [comment]
Try to clear mobile app data. To do this you need to add `persistor.purge();` at the end of `src/store/index.js`

**Comment by samsonegba** [comment]
I uninstalled the app from my physical device
I added persistor.purge(); at the end of `src/store/index.js`
ran `react-native run-android` and it installs but unfortunately its still the same

**Comment by troublediehard** [comment]
I see your problem 
<img width="177" alt="Screenshot 2020-02-28 at 16 25 47" src="https://user-images.githubusercontent.com/6594232/75556504-061d9000-5a47-11ea-8aaf-45ed54e8bfbf.png">
you have to press hide editor. In WYSIWYG editor mode it will wrap content with html tags.

**Comment by samsonegba** [comment]
Okay so I have mentioned earlier, I am new to react native and Magento. So regarding this issue, I had to figure what knowledge I was missing to be able to debug the issue, turns out I needed to learn react-redux, so I did a quick course on it.
Now I tracked to issue of sliders from the `reducers` to the `HomeSlider` component. 
Finally it turns out the images I uploaded in `magento` backend wasn't uploaded at all or perhaps wasn't uploaded to the selected directory.
About the featured products not showing, I checked the JSON and the `items` value is empty array.

Will update when I fix see why that is.

**Comment by samsonegba** [comment]
> I see your problem
> <img alt="Screenshot 2020-02-28 at 16 25 47" width="177" src="https://user-images.githubusercontent.com/6594232/75556504-061d9000-5a47-11ea-8aaf-45ed54e8bfbf.png">
> you have to press hide editor. In WYSIWYG editor mode it will wrap content with html tags.

In your code, you filtered the html tags anyways

**Comment by samsonegba** [comment]
Okay, so its fixed now, the feature product was my bad. 
When I created the categories, I selected some products during creating the category.. but apparently they didn't reflect, so I edited some products and added new categories to the product. 
Thanks you @troublediehard for this awesome system.

**Comment by troublediehard** [comment]
Welcome! 
Glad to hear you solved your issues.
