### ISSUE TITLE
can not read property 'length' of undefined.

### ISSUE THREAD

**Issue by RonakPatel0** [troublediehard/magento-react-native#121]
**Expected behavior**
on press product it open smoothly.

**Current Behavior**
when render product list I click on product so it's rise this error because. when I am wait 30s more after render product this error not rise

**Steps to Reproduce**

1. open side menu
2. select on category 
3. get products
4. press on any one product
5. See error...

**Screenshots**

![Screenshot_1582882082](https://user-images.githubusercontent.com/57698251/75536700-aec5f280-5a3b-11ea-8bd8-75170e543149.png)

**Smartphone (please complete the following information):**
 - Magento Version: [2.3.3]
 - Device: [android simulator]
 - OS: [android 9.0]

**Comment by troublediehard** [comment]
It is hard to reproduce. It probably relates to your Magento instance configuration. If you can send me your `magento.js` config privately to troublesohard@gmail.com I can try to resolve this issue.

**Comment by RonakPatel0** [comment]
I solve it out I can not get this.props.option undefined. I change some server stuff and it's work fine

**Comment by troublediehard** [comment]
@RonakPatel0 thanks for the update, I'll add the fix to prevent a crash for such cases.
