### ISSUE TITLE
Paypal Invalid Token

### ISSUE THREAD

**Issue by tmmo1230** [troublediehard/magento-react-native#122]
**Describe the bug**
When I checkout, I am getting an error message "Paypal gateway has rejected request. Invalid token (#10410: Invalid Token). May I know if Paypal checkout is supported? Thanks a lot.

**Expected behavior**
Successfully checkout with paypal

**Current Behavior**
Error message appears

![IMG_1565](https://user-images.githubusercontent.com/44220751/75803803-f93bcc00-5db9-11ea-9a96-39431ad7f054.PNG)

**Comment by troublediehard** [comment]
@tmmo1230 nope, PayPal payment method isn't implemented in the app.
