### ISSUE TITLE
when I click add to cart throw error TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by RONAKDHOLARIYA** [troublediehard/magento-react-native#124]
**Describe the bug**
when I open app and add product to cart so loader can not stop and throw error Cannot read property 'id' of null. this error rise at **RestAction.js-> addToCart function** in this customer is null because of guest user 

**Expected behavior**
in guest user work proper.

**Current Behavior**
when I open app and add product to cart so loader can not stop and throw error Cannot read property 'id' of null

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Open Product 
2. On Press Add to cart

**Screenshots**
![Screen Shot 2020-03-17 at 11 31 00 AM](https://user-images.githubusercontent.com/16955045/76826614-f40f6000-6842-11ea-8ef0-0ec8048f129b.png)

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.1.0]
 - Device: [android nexus 4]
 - OS: [android 10]

**Additional context**

**Comment by troublediehard** [comment]
```
1. Open Product
2. On Press Add to cart
```
In steps to reproduce nothing about user login, but at the same time, you said it works fine for guest user. It is not clear from your description how to reach problem conditions. 

I don't have such issues with add to cart on my Magento setup. If it is possible please send me your magento.js config privately so I can debug it on my side.

**Comment by RONAKDHOLARIYA** [comment]
when I login and after add some item to cart so it show this type of error

**Comment by troublediehard** [comment]
@RONAKDHOLARIYA can you share your config (magento.js)?

**Comment by troublediehard** [comment]
@RONAKDHOLARIYA feel free to reopen it if you have more info to help me find the problem.
