### ISSUE TITLE
Is there a way to add 2 sliders for home screen ?

### ISSUE THREAD

**Issue by RashVenkat6795** [troublediehard/magento-react-native#125]
I want to implement 2 sliders in home screen, tried configuring in cms block but its working.
Is there any way i can achieve it ?

**Comment by troublediehard** [comment]
It is not implemented to have multiple sliders on the home screen. But you can easily add it in the code ```https://github.com/troublediehard/magento-react-native/blob/master/src/components/home/HomeScreen.js```

**Comment by RashVenkat6795** [comment]
ok will check it out 
thanks for the quick response
