### ISSUE TITLE
Clicking on Country at checkout page  throws error "Error while updating property 'importantForAccessibility' of a view managed by: RCTView 

### ISSUE THREAD

**Issue by Nahyan9798** [troublediehard/magento-react-native#127]
**Describe the bug**

**Expected behavior**

**Current Behavior**
What is the current behavior?

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Navigate to...
2. Press on...
3. Scroll to...
4. See error...

**Screenshots**

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.1.0]

**Additional context**

**Comment by troublediehard** [comment]
duplicates https://github.com/troublediehard/magento-react-native/issues/128
