### ISSUE TITLE
Clicking on Country at checkout page  throws error "Error while updating property 'importantForAccessibility' of a view managed by: RCTView 

### ISSUE THREAD

**Issue by Nahyan9798** [troublediehard/magento-react-native#128]
Underneath it says "java.lang.boolean cannot be cast to java.lang.String" 

It is a local magento 2.2.11 install and latest react native version, 
I have seen your fix regarding 2 'ComponentDidMount' functions, it still does not fix this issue, 

**Expected behavior**
It should show countries to select

**Current Behavior**
Currently, it gives red screen error as described above.

**Steps to Reproduce**
1. add something to cart
2. goto checkout page
3. Enter account details, (also tried logging in and doing step 4.)
4. click on country, it will throw error
**Screenshots**

**Smartphone (please complete the following information):**
 - Magento Version: 2.2.11
 - Device: Android Emulator running android 10
 - OS: Android Q

**Comment by troublediehard** [comment]
@Nahyan9798 can share a stack trace of the error or attach a screenshot of the screen with error?

**Comment by Nahyan9798** [comment]
![Screenshot from 2020-04-22 14-57-26](https://user-images.githubusercontent.com/64132029/79968492-9ad1c680-84a9-11ea-8763-010dc0606e68.png)


![Screenshot from 2020-04-22 14-08-59](https://user-images.githubusercontent.com/64132029/79968351-665e0a80-84a9-11ea-9069-8becbbd803df.png)

This is the error when i touch country.

I would love to figure this error out but i am lost as to where i should start, thank you for replying so quickly

**Comment by troublediehard** [comment]
@Nahyan9798 fixed. Please take a look.

**Comment by Nahyan9798** [comment]
I made the changes to yarn.lock and packages.json as seen in the pr, but still the issue persists

**Comment by troublediehard** [comment]
@Nahyan9798 did you install dependencies like `npm install` or `yarn install` ?

**Comment by Nahyan9798** [comment]
Yes, Yes I did

**Comment by troublediehard** [comment]
@Nahyan9798 I've just checked again. I can reproduce issue with old version of `react-native-modal-selector` and can't with new. Probably some cache issue on your end. Try remove the app from emulator and build it again.

**Comment by Nahyan9798** [comment]
I tried deleting the app and building again, still the same issue, connected to physical device and installed but still issue persists,
if you could kindly suggest some things  i could try to resolve the issue, i would be very thankful

**Comment by troublediehard** [comment]
@Nahyan9798 check version in `node_modules/react-native-modal-selector/package.json`

**Comment by Nahyan9798** [comment]
shows version 2.0.1

**Comment by Nahyan9798** [comment]
![Screenshot from 2020-04-22 19-24-22](https://user-images.githubusercontent.com/64132029/79994038-e480d800-84ce-11ea-98b7-fb5c05943b1a.png)
there seems to be a problem here, bundleDependencies expects an array but is receiving just false, could this be the issue?

**Comment by Nahyan9798** [comment]
nevermind this is the same for all dependencies, issue is something else

**Comment by troublediehard** [comment]
@Nahyan9798 Looks like it is related to the data you pass to the modal selector, you can try to log it
<img width="570" alt="Screenshot 2020-04-22 at 17 35 32" src="https://user-images.githubusercontent.com/6594232/79995340-c95a9c00-84bf-11ea-996f-9bab51e89a07.png">

**Comment by troublediehard** [comment]
I think also relates https://github.com/peacechen/react-native-modal-selector/issues/143

**Comment by Nahyan9798** [comment]
It worked! 
Changing these two parameters in node_modules/react-native-modal-selector/index.js from undefined to " " worked.
 scrollViewAccessibilityLabel:   "",
    cancelButtonAccessibilityLabel: "", 
Thank you for solving this issue! 
On which countries does order button show up? i am selecting US and region as new york yet shipping address  is not found for this selected address

Again Thanks a bunch for solving this issue.

**Comment by alexakasanjeev** [comment]
> I think also relates [peacechen/react-native-modal-selector#143](https://github.com/peacechen/react-native-modal-selector/issues/143)

Hi @troublediehard I'm too having the same issue on my project, bumped the `react-native-modal-selector` version, and working fine, do I have to do something else too apart from it, I didn't understand what else need to be set?

**Comment by troublediehard** [comment]
hey @alexakasanjeev, I think after upgrade library it is still possible to reproduce this issue in some cases. But I don't dive into it a lot, so I'm going to keep this issue open for now.

**Comment by peacechen** [comment]
This has been fixed and published in 2.0.2.

**Comment by troublediehard** [comment]
@peacechen thank you for the update.
