### ISSUE TITLE
Please add related products and reviews in the product page.

### ISSUE THREAD

**Issue by SubhadipDutta93** [troublediehard/magento-react-native#129]
**Please add related products in the product page.**
Once a customer clicks on the product, on the product page there should be some related product also. when a customer clicks on the related product it will show the product with product details.

**Please add reviews of the product in the product page.**
On the product page, customers should be able to see the product review of that specific product and also can submit their reviews and rating.

**Comment by troublediehard** [comment]
@alexakasanjeev would you like to migrate this functionality from the Lyon project? I think it is good to have it here, but I'm not sure when I'll have time to work on it.

**Comment by troublediehard** [comment]
how to fetch related products
https://magento.stackexchange.com/a/165222/28975

**Comment by alexakasanjeev** [comment]
> @alexakasanjeev would you like to migrate this functionality from the Lyon project? I think it is good to have it here, but I'm not sure when I'll have time to work on it.

Sure, I will move the UI logic, but probably need your input, on what are the API need to be hit, because if I remember, for review, you wrote custom plugin, correct?

**TODO**
- [ ] Add Review related component in Product screen
- [ ] Add Horizontal list to show related product in Product Screen

**Comment by troublediehard** [comment]
@alexakasanjeev sure, feel free to reach me with any questions. Following Magento module is required for reviews https://github.com/troublediehard/mma-customapi.

**Comment by RashVenkat6795** [comment]
@alexakasanjeev You implemented this feature ? If so can you please guide me on how to do it.

**Comment by alexakasanjeev** [comment]
@RashVenkat6795 I will implement in this repo soon, you can simply take a clone and see :)

**Comment by alexakasanjeev** [comment]
Hi @troublediehard I'm working on related products, but there is a small hurdle. As clicking on related products will again launch `ProductScreen` thus overwriting the `current` variable value in `ProductReducer`, so when we will press back, we won't see the parent product but the same child product which was clicked.

This is because of how the state is setup, you extracted the `current` product logic in `Lyon` to support this problem, but not here.

So either you can perform this on your own or if you want me, I can try to move the logic of how `ProductScreen` works by going through the commit in `Lyon` of how you did?

**Comment by troublediehard** [comment]
@alexakasanjeev yes, please go ahead. Let me know if something not clear in my implementation.

**Comment by alexakasanjeev** [comment]
@troublediehard I have created a PR with **Related Products** in Product Detail Screen. There is one problem, please read the text in PR body

**Comment by troublediehard** [comment]
@alexakasanjeev well done! Can you pick the product review as well?

**Comment by troublediehard** [comment]
@SubhadipDutta93 @RashVenkat6795 related products functionality now in the master branch.

**Comment by alexakasanjeev** [comment]
@troublediehard I reported one problem, with related product, in PR, did you check?

About `product review` you have written custom plugin for magento `mma/customapi` that lets access to review API, but I don't have much knowledge of magento server side, I don't know how to install,

you have mentioned installation instructions 
```
composer require mma/customapi
php bin/magento setup:upgrade
php bin/magento cache:clean
```

do I need to clone the repo, and paste it somewhere before running `composer require mma/customapi` ??

**Comment by troublediehard** [comment]
@alexakasanjeev I've just checked and I need to do one thing before you can use the installation method as you mentioned. I'll back to you when it is done.

**Comment by troublediehard** [comment]
@alexakasanjeev I've upgraded version to `0.5.9`. Now it should work simply with 
```
composer require mma/customapi
php bin/magento setup:upgrade
php bin/magento cache:clean
```

**Comment by SubhadipDutta93** [comment]
> @SubhadipDutta93 @RashVenkat6795 related products functionality now in the master branch.

I've also done the same and working on the review part.

**Comment by troublediehard** [comment]
> @troublediehard I reported one problem, with related product, in PR, did you check?

@alexakasanjeev yes, I did refactoring off Product screen and change related products logic.

**Comment by troublediehard** [comment]
@SubhadipDutta93 great! Feel free to make PR if you like to contribute.
