### ISSUE TITLE
error after install apk

### ISSUE THREAD

**Issue by benyang2015** [troublediehard/magento-react-native#13]
<img width="248" alt="221" src="https://user-images.githubusercontent.com/15188607/44947477-12b82c80-ae40-11e8-91f1-a985b5595307.png">

**Comment by troublediehard** [comment]
@benyang2015 are you using windows? 
Regarding this thread https://github.com/facebook/react-native/issues/14209 there is some issue with react-native 0.56 on windows, so possible solution is a downgrade to 0.55.4. And in 0.57 it is expected to be fixed.

**Comment by benyang2015** [comment]
I‘m use mac

**Comment by troublediehard** [comment]
@benyang2015 sorry didn't receive notification on your reply. I can't reproduce this on my end. There is a lot of suggestion over the internet for a similar issue, for example, https://stackoverflow.com/questions/44795384/unable-to-load-script-from-assets-index-android-bundle-make-sure-your-bundle/45409223#45409223. Did you try any?

**Comment by izuku-franck1555** [comment]
![screenshot_1536675706](https://user-images.githubusercontent.com/43177617/45367197-a1634100-b5d8-11e8-8e83-0124b8a3ac95.png)
Please i have the same problem... help me @troublediehard... i use windows.

**Comment by izuku-franck1555** [comment]
I finally solved my problem but I do not understand this step :  
"Put your config inside Content section (config sample)"
please help me

**Comment by izuku-franck1555** [comment]
![screenshot_1536684879](https://user-images.githubusercontent.com/43177617/45375036-cad99800-b5eb-11e8-95a9-2c8f06abff4b.png)
that is my presently screen !!!

**Comment by izuku-franck1555** [comment]
![screenshot_1536685078](https://user-images.githubusercontent.com/43177617/45375224-3cb1e180-b5ec-11e8-8f6a-08c2ef4ce20c.png)

**Comment by troublediehard** [comment]
@izuku-franck1555 you need to put your config inside cms block in Magento admin like on screenshot 
<img width="1418" alt="screenshot 2018-09-12 11 15 03" src="https://user-images.githubusercontent.com/6594232/45411615-52bbb280-b67d-11e8-9afe-f0999e4d66c6.png">

**Comment by izuku-franck1555** [comment]
thank you for answering @troublediehard ... I'm going to try.

**Comment by izuku-franck1555** [comment]
But I'm still slightly lost ... Where am I supposed to find my config.

**Comment by izuku-franck1555** [comment]
I understood many things today ... In fact it is me who must create my own configuration because the config is the way the page will be arranged.

**Comment by izuku-franck1555** [comment]
At present I have four problems:
The first is that there are only two categories in the application, yet I have 8.
The second is that I do not see any product when I click on a category.
The third is where to learn json to create my own config
The last problem is that I have an error message at any time and I do not know if it's the one that causes the other errors.
I am only an apprentice so please help me @troublediehard .

**Comment by izuku-franck1555** [comment]
![01](https://user-images.githubusercontent.com/43177617/45428396-10a06a00-b699-11e8-9904-01ab6e32199c.jpg)
![Uploading 02.jpg…]()
![Uploading 03.png…]()

**Comment by izuku-franck1555** [comment]
![02](https://user-images.githubusercontent.com/43177617/45428444-231aa380-b699-11e8-98f7-80b7a2c81b96.jpg)
![03](https://user-images.githubusercontent.com/43177617/45428399-11390080-b699-11e8-8fd7-31fe16223c5d.png)

**Comment by izuku-franck1555** [comment]
Ok I create a slack account and I join you.

**Comment by troublediehard** [comment]
a bunch of issues mentioned so thread became unclear.
