### ISSUE TITLE
How to get the product reviews and attributes like size, weight, color ? 

### ISSUE THREAD

**Issue by RashVenkat6795** [troublediehard/magento-react-native#130]
Hi,
I want to get the product attributes like size, weight, color..... and also the reviews posted for the product.
How can i get that ?

**Comment by troublediehard** [comment]
I believe it's already inside the app in product data. Please clarify your question?

**Comment by RashVenkat6795** [comment]
But the product data returns values in numbers and attribute codes

**Comment by troublediehard** [comment]
You can fetch attribute details by code with https://devdocs.magento.com/swagger/#/catalogProductAttributeRepositoryV1/catalogProductAttributeRepositoryV1GetGet

**Comment by RashVenkat6795** [comment]
Thanks will try this!
