### ISSUE TITLE
Buy now option

### ISSUE THREAD

**Issue by RAGHURAMK0542** [troublediehard/magento-react-native#132]
@troublediehard 
Hi 
I am trying to implement buynow option, so in product.js
i've used the same function of yours onPressAddToCart and after which i just added this.props.navigation.push(NAVIGATION_HOME_CART_PATH)

so that it takes me back to the cart where in i can complete the transaction, after transaction completion it takes me back to home screen, i am getting blank cart, how to make it refresh to go back to home screen

is there any better way to implement this feature

**Comment by troublediehard** [comment]
hi @RAGHURAMK0542, I don't really understand your question. Do you want to navigate to the home screen after 'place order' ?

**Comment by RAGHURAMK0542** [comment]
@troublediehard,  it is navigating to the home screen but instead of home page details its showing empty cart screen

**Comment by troublediehard** [comment]
Can you share your navigation code? I don't know where NAVIGATION_HOME_CART_PATH route points.

**Comment by RAGHURAMK0542** [comment]
import Cart from '../components/cart/Cart';

const HomeStack = createStackNavigator(
  {
    [routes.NAVIGATION_HOME_SCREEN_PATH]: HomeScreen,
    [routes.NAVIGATION_CATEGORY_PATH]: Category,
    // [routes.NAVIGATION_HOME_PRODUCT_PATH]: Product,
    [routes.NAVIGATION_HOME_PRODUCT_PATH]: Product,
    [routes.NAVIGATION_SEARCH_SCREEN_PATH]: SearchScreen,
    [routes.NAVIGATION_SEARCH_PRODUCT_PATH]: Product,
    [routes.NAVIGATION_HOME_CART_PATH]: Cart
  },
  {
    initialRouteName: routes.NAVIGATION_HOME_SCREEN_PATH,
    navigationOptions: defaultHeader,
  },
);

This is how i've used it

**Comment by troublediehard** [comment]
so by doing `this.props.navigation.push(NAVIGATION_HOME_CART_PATH)` you navigate to `[routes.NAVIGATION_HOME_CART_PATH]: Cart` Cart component. If you want a different screen here, you should use another route.

**Comment by RAGHURAMK0542** [comment]
Yes i've used this 
`this.props.navigation.push(NAVIGATION_HOME_CART_PATH)` on the **onPressAddToCart**. So if i just press add to cart button, the product will be added to cart and then it will be navigated to cart screen, and i complete the payment purchase, so on successful transaction completion it will be navigated back to home screen, but the details of home screen are not showing instead its showing the empty cart screen

**Comment by troublediehard** [comment]
Sorry, I still can't understand your issue. Maybe you can record your screen and show me what is happens on your end?

**Comment by RAGHURAMK0542** [comment]
ok sure i will do that

**Comment by RAGHURAMK0542** [comment]
Please find the video record here 
https://drive.google.com/file/d/1vzrbVO6tvr1UeX3AKtx0yWy_aXfOANfN/view?usp=sharing

**Comment by troublediehard** [comment]
ok, now I got it

Check `goHome` function in `src/components/checkout/CheckoutTotals.js` it points to the `NAVIGATION_HOME_STACK_PATH` after place order. You have cart screen on top of your home stack so it backs to it. 

I don't have a solution for you here, but you can try to modify `goHome` function to archive what you want.

**Comment by troublediehard** [comment]
Please reopen the issue if you have more questions.
