### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by akhilunitybees** [troublediehard/magento-react-native#134]
Please add Wish List and user review

**Comment by troublediehard** [comment]
@akhilunitybees I've just added reviews functionality to the product screen. To use it you have to install https://github.com/troublediehard/mma-customapi on your magento backend and set 
```
export const magentoOptions = {
  // ...
  reviewEnabled: true, // ONLY if you install https://github.com/troublediehard/mma-customapi
};
```
in `src/config/magento.js`

**Comment by troublediehard** [comment]
Regarding the wishlist, I don't have any plans to add it in near future.
