### ISSUE TITLE
Android app  - Compilation - Network Request Failed

### ISSUE THREAD

**Issue by Ank1304** [troublediehard/magento-react-native#141]
**Describe the bug**
The app throws error : "Network request failed" on launch

**Expected behavior**
The app should open the store when launch the android app

**Current Behavior**
The app launches just fine, but on launch - at the home page, it throws error : Network request failed. It is as if the app is not even able to communicate with the internet 

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Compile the app using gradlew clean && gradlew assembleRelease -x bundleReleaseJsAndAssets with the store settings in magento.js
2. Move the apk to android phone 
3. Install the app 
4. At the home page : "Network Request failed"

**Screenshots**

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.4]
 - Device: Redmi K20 Pro
 - OS: Android
 - Version 9

**Additional context**
If you need additional info, please let me know, I will share it

**Comment by troublediehard** [comment]
@Ank1304 please try https://github.com/facebook/react-native/issues/24627#issuecomment-492159371. Let me know if it helps or not.

**Comment by troublediehard** [comment]
hey @Ank1304,
do you have trails slash in the end of your website URL like in `magento-sample.js` ?
```
url: 'http://mage2.local/', // make sure you have trail slash in the end
```

**Comment by Ank1304** [comment]
hey @troublediehard 

I do have a trailing slash at the end. I think this could be because of the fetch library. Do you have any alternative that we can use instead of fetch ?

**Comment by troublediehard** [comment]
share logs from `Remote JS Debugging` https://reactnative.dev/docs/debugging

**Comment by troublediehard** [comment]
@Ank1304 did you solve it?
