### ISSUE TITLE
unable to retrieve current customer Error: The consumer isn't authorized to access self

### ISSUE THREAD

**Issue by iMohamedSamir** [troublediehard/magento-react-native#142]
**Describe the bug**
The app failed to load categories in the homepage.

**Expected behavior**
load categories in the homepage.

**Current Behavior**
The app failed to load categories in the homepage.

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. open app
2. login
3. press r to open debugger
3. open inspector console
3. reload the app

**Screenshots**

![S8guX3O](https://user-images.githubusercontent.com/3066796/92289172-d24c8700-ef0f-11ea-8cec-fc28ed34abb3.png)

**Smartphone (please complete the following information):**
 - Magento Version: [2.3.5-p1]
 - Device: [Pixel 3 XL]
 - OS: [Android]
 - Version [11]

**Additional context**
I think this issue is not related to magento-react-native specifically, but I am still digging.
Also it is not permission related issue, I sure I gave all access to the access token account.

**Comment by troublediehard** [comment]
Hi @iMohamedSamir,

The error on your screenshot isn't related to the admin token in your config file. It's related to the customer token you get after login. But I don't think it somehow breaks your home screen. 

1. Did your categories load fine before you did login? 
2. Share your home screen cms config.

**Comment by alexakasanjeev** [comment]
Hi @iMohamedSamir 

By default, customer token generated when user login is valid for 1 hour. You can change these values from Admin by selecting **Stores > Settings > Configuration > Services > OAuth > Access Token Expiration.**

There, increase the customer token expiry time to 168hours(7 days) or according to your need

@troublediehard  I would suggest you to add this steps in setup guide.

**Comment by troublediehard** [comment]
Thanks, @alexakasanjeev, good point. But I want to note it doesn't relate to the reported issue 
```
Describe the bug
The app failed to load categories in the homepage.

Expected behavior
load categories in the homepage.
```

**Comment by iMohamedSamir** [comment]
Yeah, my bad, I had completely two separate issues and I thought they were related
And thanks @troublediehard
