### ISSUE TITLE
Android Navigation Icons missing

### ISSUE THREAD

**Issue by Mivanov9** [troublediehard/magento-react-native#143]
**Describe the bug**
When loading into the app on an Android emulator causes warnings and the navigation buttons to have either missing or wrong icons.

**Expected behavior**
Proper icons to appear, as seen in the demo video.

**Current Behavior**
Incorrect icons loading and warnings 

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Load app
2. Warnings appear at bottom of screen and icons are incorrect
**Screenshots**
![Screenshot 2020-09-11 163552](https://user-images.githubusercontent.com/51979821/92970887-78871800-f44d-11ea-8025-8bc41ba41f9b.png)

![Screenshot 2020-09-11 163559](https://user-images.githubusercontent.com/51979821/92970894-7c1a9f00-f44d-11ea-9456-9bc508a4b67a.png)

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.4.0]
 - Device: [Pixel 3]
 - OS: [10 (Q)]

**Comment by troublediehard** [comment]
I've just tested it with android emulator Pixel 3 Android 10 Q. And I can't reproduce it on my end. Looks like something wrong on your end during build process. Fonts from `react-native-vector-icons` isn't attached correctly. Try to clean project and build it again. Also, you can try to find a similar issues in https://github.com/oblador/react-native-vector-icons/issues. 

![Screenshot_1599861652](https://user-images.githubusercontent.com/6594232/92977228-1c47e680-f495-11ea-805d-32bf7ebce1b8.png)

**Comment by troublediehard** [comment]
For example, try this https://github.com/oblador/react-native-vector-icons/issues/1228#issuecomment-686772521

**Comment by Mivanov9** [comment]
I was able to fix the issue I was having it works perfectly fine now, but I did it by
removing the '^' from the package.json :
-"react-native-vector-icons": "^6.6.0" -> "react-native-vector-icons": "6.6.0"
then removing and reinstalling the node_modules

Here is the link I found the solution from, it was describing an issue I had before where the app would not launch at all but previously I just installed @react-native-community/toolbar-android manually which led to the issue I posted.

https://github.com/oblador/react-native-vector-icons/issues/1193

**Comment by troublediehard** [comment]
@Mivanov9 thanks for sharing.
