### ISSUE TITLE
Checkout button in the ProductScreen.js file

### ISSUE THREAD

**Issue by sid3291** [troublediehard/magento-react-native#144]
I would like to add a checkout button under the cart button in the ProductScreen.js file. That way, the user would be able to buy the product directly from its screen, without passing through the cart. How would I be able to do so?

**Comment by troublediehard** [comment]
hi @sid3291,
I think steps should be like
1. Wait response for add to cart request.
2. Update cart. 
3. Navigate to the checkout screen.
