### ISSUE TITLE
Use react-native-render-html library to render product description

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#145]
**Is your feature request related to a problem? Please describe.**
Currently, if product description comes as `HTML` content, you strip out html tags, and render product description into simple `Text` component.

**Describe the solution you'd like**
[react-native-render-html](https://github.com/archriss/react-native-render-html) library helps to render HTML content easily, hence product description can be render as set from admin

1. Install `webview` & `react-native-render-html` library
2. Use the library to render product description

**Additional context**
Example Screenshot how it will look like
![Screenshot_1601619494](https://user-images.githubusercontent.com/13250741/94893776-98868600-04a5-11eb-9d87-cc964adc345a.png)

@troublediehard do you want this, I can work on it???

**Comment by troublediehard** [comment]
@alexakasanjeev yes, good point. I've already tested it in https://github.com/troublediehard/magento-react-native-2. So if you have time please go ahead.

**Comment by alexakasanjeev** [comment]
Are you using `Product.js` because I can still see this file, and I think you are using `ProductScreen.js` to render product details.

shall I delete it?

**Comment by troublediehard** [comment]
1. yes, remove it
2. remove it as well
