### ISSUE TITLE
"Network Request Failed" Error in the Signup

### ISSUE THREAD

**Issue by kanhucd** [troublediehard/magento-react-native#149]
**Describe the bug**
"Network Request Failed" Error in the Signup After I fill the form and submit.

**Expected behavior**
Signup should return successful message and allow login with that user.

**Current Behavior**
"Network Request Failed" Error on clicking submit.

**Screenshots**
![Screenshot_20201006-204407_magento_mobile_app](https://user-images.githubusercontent.com/43762141/95221309-f0f6b400-0814-11eb-9e3b-33bdb666f792.jpg)

 - Magento Version: 2.3.5
 - Device: Note8
 - OS: Android
 - Version: 9

**Comment by troublediehard** [comment]
@kanhucd Can you share logs from remote debugger?

**Comment by troublediehard** [comment]
@kanhucd I can't reproduce this issue on my end. Feel free to reopen this issue if you ready to elaborate and provide more details.

**Comment by kanhucd** [comment]
Hii @troublediehard, Sorry for the delay. 

Below is the Error I am getting with Php 7.3 for Magento 2.3.5.
**[2020-10-15 16:36:44] main.CRITICAL: Report ID: webapi-5f887a9c712d8; Message: Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /home3/craftoindia/public_html/vendor/laminas/laminas-validator/src/EmailAddress.php on line 560 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5f887a9c712d8; Message: Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /home3/craftoindia/public_html/vendor/laminas/laminas-validator/src/EmailAddress.php on line 560 at /home3/craftoindia/public_html/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /home3/craftoindia/public_html/vendor/laminas/laminas-validator/src/EmailAddress.php on line 560 at /home3/craftoindia/public_html/vendor/magento/framework/App/ErrorHandler.php:61)"} []**

But when I upgrade to php 7.4 I get the below Error:
**[2020-10-15 16:42:27] main.ERROR: Notice: Trying to access array offset on value of type null in /home3/craftoindia/public_html/vendor/magento/framework/App/AreaList.php on line 78 [] []
[2020-10-15 16:42:27] main.CRITICAL: Notice: Trying to access array offset on value of type null in /home3/craftoindia/public_html/vendor/magento/framework/App/AreaList.php on line 78 {"report_id":"9434cf0a73958ad5da6ac13a1c05a5104bbeb653e461a27ed7c4a946e0a12289","exception":"[object] (Exception(code: 0): Notice: Trying to access array offset on value of type null in /home3/craftoindia/public_html/vendor/magento/framework/App/AreaList.php on line 78 at /home3/craftoindia/public_html/vendor/magento/framework/App/ErrorHandler.php:61)"} []**

**Comment by troublediehard** [comment]
@kanhucd looks like an error on the Magento 2 side, you should investigate it there.

**Comment by troublediehard** [comment]
@kanhucd also, if share your config `src/config/magento.js` I can take a look on my end.

**Comment by kanhucd** [comment]
@troublediehard  Have uploaded the js file..
[magento.zip](https://github.com/troublediehard/magento-react-native/files/5389055/magento.zip)

**Comment by troublediehard** [comment]
I've tested on my end and I can confirm there is nothing wrong on the mobile app side. You should fix it on the Magento backend. 

<img width="443" alt="Screenshot 2020-10-16 at 11 44 09" src="https://user-images.githubusercontent.com/6594232/96236668-00a89200-0fa5-11eb-90fc-beadf292215f.png">
<img width="690" alt="Screenshot 2020-10-16 at 11 44 06" src="https://user-images.githubusercontent.com/6594232/96236679-030aec00-0fa5-11eb-8ff5-41ad0a7b3a6a.png">
