### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by alamengo09** [troublediehard/magento-react-native#150]
I am having problems with my product`s description. how can I format this variable so my description can look nicer?

**Comment by troublediehard** [comment]
@alamengo09 what problem do you have?

**Comment by troublediehard** [comment]
@alexakasanjeev can you suggest anything on description formatting?

**Comment by alexakasanjeev** [comment]
[react-native-render-html](https://github.com/archriss/react-native-render-html) library provides props to customize text

props like `baseFontStyle`, `containerStyle` etc 

@alamengo09 check [docs](https://github.com/archriss/react-native-render-html)

**Comment by sid3291** [comment]
![image](https://user-images.githubusercontent.com/66479859/95492006-d5a0bb80-0970-11eb-87f3-277477c116d2.png)
![Screenshot_1602177447](https://user-images.githubusercontent.com/66479859/95492136-05e85a00-0971-11eb-9c90-c56f3f0cabe3.png)


The first picture is how it is on my store's web page, the second one is how it is on the app

**Comment by troublediehard** [comment]
@sid3291 
Looks like you have some CSS styles in the web version. The latest version of the app uses `react-native-render-html` lib to render description.  Try to apply styles with `tagsStyles`, `classesStyles`. For more information check library [docs](https://github.com/archriss/react-native-render-html#props).
