### ISSUE TITLE
updateUI

### ISSUE THREAD

**Issue by sidneylopes** [troublediehard/magento-react-native#152]
I added an input to my CheckoutPaymentMethod so the person can enter their taxvat code, but the updateUI does not work. It deletes everything that I type in. Here is the input's code:

<Input
autoCapitalize="none"
label={translate('common.taxvat')}
value={this.props.taxvat}
placeholder={translate('common.taxvat')}
onChangeText={value => this.updateUI('taxvat', value)}
/>

**Comment by troublediehard** [comment]
there is no `updateUI` function

**Comment by sid3291** [comment]
Yes, there is. Look:

updateUI = (key, value) => {
  this.props.updateCheckoutUI(key, value);
};

**Comment by troublediehard** [comment]
really? 
https://github.com/troublediehard/magento-react-native/blob/master/src/components/checkout/CheckoutPaymentMethod.js

**Comment by sid3291** [comment]
I added the function

**Comment by troublediehard** [comment]
How do you path `updateCheckoutUI` to props? 
```
this.props.updateCheckoutUI(key, value);
```

**Comment by sid3291** [comment]
export default connect(mapStateToProps, {
  checkoutSelectedPaymentChanged,
  updateCheckoutUI,
  checkoutSetActiveSection,
  getGuestCartPaymentMethods,
  checkoutCustomerNextLoading,
})(CheckoutPaymentMethod);

**Comment by troublediehard** [comment]
and `taxvat` value?

**Comment by sid3291** [comment]
it comes from customer. I call it as customer.taxtvat.

**Comment by troublediehard** [comment]
I don't understand. 

You pass value from input to the `this.updateUI('taxvat', value)` and set `value={this.props.taxvat}` somewhere from `customer.taxtvat`, right?

```
<Input
autoCapitalize="none"
label={translate('common.taxvat')}
value={this.props.taxvat}
placeholder={translate('common.taxvat')}
onChangeText={value => this.updateUI('taxvat', value)}
/>
```

**Comment by sid3291** [comment]
I think so

**Comment by troublediehard** [comment]
ok, I don't understand what you are doing and how it should work. 

basically logic of Input should look like this
```
  ...
  const [value, setValue] = useState('');
  ...
  return (
    <Input
      value={value}
      onChangeText={value => setValue(value)}
    />
  )
```
so you get value `onChangeText` do whatever you need to do with it and then pass the result to `value` prop.

**Comment by sidneylopes** [comment]
Thanks. problem solved hahaha
