### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by sidneylopes** [troublediehard/magento-react-native#153]
Every time that my code tries to print an error message, I get an error, and the message is shown in the console instead. How can a print it so the user can see it?

![Screenshot from 2020-10-28 14-32-53](https://user-images.githubusercontent.com/66479859/97474185-98559b00-192a-11eb-9b17-61085b12442c.png)

**Comment by troublediehard** [comment]
hey @sidneylopes. Each time you ask a question like `My code doesn't work` and you don't share your code I can't really help you because I've never seen your code. Can you please be more respectful of my time and provide your code first.

**Comment by sidneylopes** [comment]
![image](https://user-images.githubusercontent.com/66479859/97484166-2d5e9100-1937-11eb-9fdd-86ef7b959a97.png)

**Comment by troublediehard** [comment]
@sidneylopes I was able to replicate and fix the issue, please check https://github.com/troublediehard/magento-react-native/commit/cac6929cca36ae2c097ca86a206153e9d09dc7cb

**Comment by sidneylopes** [comment]
I tried, but no different results

**Comment by troublediehard** [comment]
@sidneylopes what exactly did you tried? 
I was able to reproduce the issue and the fix is working for me.

**Comment by sidneylopes** [comment]
in the index, I changed "Promise.reject(errorResponse);" to "reject(errorResponse);", but nothing happened. Should I try printing something else?

**Comment by troublediehard** [comment]
Probably js bundler cache, try to restart it and remove the app from the simulator.

**Comment by sidneylopes** [comment]
It worked, thanks. Sorry about yesterday!

**Comment by troublediehard** [comment]
no problem, glad you solved it.
