### ISSUE TITLE
Cupon problem

### ISSUE THREAD

**Issue by sidneylopes** [troublediehard/magento-react-native#155]
When I try to submit valid cupon codes, I get this error, which I have no idea on how to solve it.
![Screenshot_1604430630](https://user-images.githubusercontent.com/66479859/98030187-6db68700-1def-11eb-8a79-1c9325920f2a.png)

**Comment by troublediehard** [comment]
I've tried on my end and it's working as expected. 
Probably you did some additional steps to reproduce this issue. Or you did some changes in code which cause this error. 

![simulator_screenshot_5D18D8D3-644D-4E75-8FD0-9E0D4EED7F67](https://user-images.githubusercontent.com/6594232/98042827-e4be4080-1e2c-11eb-9f0a-5e85451eddfd.png)

**Comment by troublediehard** [comment]
@sidneylopes can you reproduce this issue on a clean copy of this repository? I mean if you check out this project from github without your modifications and try to reproduce.

**Comment by sidneylopes** [comment]
same problem

![WhatsApp Image 2020-11-06 at 1 44 49 PM](https://user-images.githubusercontent.com/66479859/98392087-49002080-2036-11eb-96bc-10dc6fdce676.jpeg)

**Comment by troublediehard** [comment]
@sidneylopes can you remove the app and after fresh install record the video with all actions from the app start to coupon error? In this case, I can see all steps and probably can reproduce the issue on my end.

**Comment by sidneylopes** [comment]
The link to the video on google drive:

https://drive.google.com/file/d/13qXG3cp4znssnwINeTHqLfTcsfNAhAP9/view?usp=sharing

**Comment by troublediehard** [comment]
Sorry, but it's not what I asked
1. Quality is bad, I can't see text on screen.
2. You didn't record reproduces on a fresh install, you did some actions like login, add the product to cart, and probably something else, which is important steps they could lead to the issue.

**Comment by sidneylopes** [comment]
The red sentence that appears is the error that I sent earlier. I also used a fresh install. I added the product to the cart because it is the only way to go to the checkout page. The error also only happens when somebody is logged in.

**Comment by sidneylopes** [comment]
Try reproducing the error by logging in with an account
