### ISSUE TITLE
Signup Loading Forever

### ISSUE THREAD

**Issue by arecastudio** [troublediehard/magento-react-native#157]
**Are there certain things to report that are not a bug or feature?**
Please tell us as exactly as possible about your request, thanks.
We will reply as soon as possible.

Hi, I can install the app for testing, but when first running I tried to register new user, its takes forever loading on screen without showing user information. It can only success if I logging out first then logging in,

**Comment by troublediehard** [comment]
Hi Israil,
1. can you check if there any error in the remote debugger logs? https://reactnative.dev/docs/debugging#chrome-developer-tools
2. Can you record screen with bug reproducing?

**Comment by troublediehard** [comment]
@arecastudio did you solve the issue?
