### ISSUE TITLE
Problems when adding an address

### ISSUE THREAD

**Issue by sidneylopes** [troublediehard/magento-react-native#158]
When I press the Add Address button, I have the following error:

![Screenshot_1605285693](https://user-images.githubusercontent.com/66479859/99097363-495c6680-25b6-11eb-9d5a-a32b02368ec5.png)

Here is the part of the code that has "countries.find":

const country = countries.find(item => item.id === countryId);

How can I fix it (my app is only for Brazil)?

**Comment by sidneylopes** [comment]
I also just noticed that the error doesn't happen every time

**Comment by troublediehard** [comment]
1. Can you share reproduce steps?
2. Are you using persist state? 
3. If you don't a universal solution for any country configured from the Magento side, you can hardcode Brazil value.
