### ISSUE TITLE
AppRegistry

### ISSUE THREAD

**Issue by sidneylopes** [troublediehard/magento-react-native#159]
I need to change the app registry, but when I do so, I get an error. Where else do I have to change it?

![Screenshot_1605728005](https://user-images.githubusercontent.com/66479859/99578628-db4fdf00-29bb-11eb-8e57-ddae3078eefd.png)

**Comment by troublediehard** [comment]
@sidneylopes have you tried the solution from the docs https://github.com/troublediehard/magento-react-native/wiki/Rename-Project ?

**Comment by sidneylopes** [comment]
sorry, I didn't see it. It worked, thanks
