### ISSUE TITLE
Show this Error on android

### ISSUE THREAD

**Issue by MzkZeeshan** [troublediehard/magento-react-native#16]
![img_20181117_205140537](https://user-images.githubusercontent.com/36148341/48722896-07a6b880-ec47-11e8-8c70-ad3a556c8702.jpg)

**Comment by troublediehard** [comment]
@MzkZeeshan try to check following https://github.com/react-community/create-react-native-app/issues/721

**Comment by MzkZeeshan** [comment]
but i am create new project  rect-natvie cli it work but your project is not working

**Comment by troublediehard** [comment]
what is version of React Native you created? Did you check my response on the GitHub?

**Comment by MzkZeeshan** [comment]
0.56.0

**Comment by troublediehard** [comment]
what command are you used to create new project?

**Comment by MzkZeeshan** [comment]
react-native init NewProject

**Comment by troublediehard** [comment]
@MzkZeeshan you can find a lot of solution in the internet related to the issues for example here https://stackoverflow.com/questions/48756550/unable-to-resolve-module-accessibilityinfo-when-trying-to-create-release-bund. It is bug not related specifically to this project, but something inside react native with Windows combo (as I understand from info in the internet). I don't have Windows and can't reproduce this issues, so It is hard to understand what exactly wrong on your end. 

If you find how to resolve it, please post you solution here.

**Comment by MzkZeeshan** [comment]
ok

**Comment by MzkZeeshan** [comment]
I am having this warning isMounted(...) is deprecated in plain Javascript classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
This warning shows up when transitioning from collapsed to non-collapsed. I tried to find where isMounted is used in the code but with no luck. and my order is not placed

**Comment by MzkZeeshan** [comment]
and previous Error Resolve this way first delete node_modules folder  and in package.json
change react-native version "react-native": "0.55.2", and
  babel "babel-preset-react-native": "4", after that run yarn install or
npm install and run its work fine for me.

**Comment by troublediehard** [comment]
> I am having this warning isMounted(...) is deprecated in plain Javascript classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
> This warning shows up when transitioning from collapsed to non-collapsed. I tried to find where isMounted is used in the code but with no luck. and my order is not placed

It is not used in the project directly, most likely it is some of the dependencies. But deprecation isn't error, it is only mean that it will not be used in a future release, so I'm not going to check it until it is really necessary.

**Comment by troublediehard** [comment]
> and previous Error Resolve this way first delete node_modules folder and in package.json
> change react-native version "react-native": "0.55.2", and
> babel "babel-preset-react-native": "4", after that run yarn install or
> npm install and run its work fine for me.

thanks for sharing this.

**Comment by MzkZeeshan** [comment]
but my order is not placed

**Comment by MzkZeeshan** [comment]
this application say your order is placed but when i check in  admin in Dashboard no order there

**Comment by troublediehard** [comment]
check place order request response.

**Comment by MzkZeeshan** [comment]
Order placed successfully but ordre is not done

**Comment by troublediehard** [comment]
order not placed if there is no order in admin

**Comment by troublediehard** [comment]
so place order request should return some error

**Comment by MzkZeeshan** [comment]
NO Error Show

**Comment by troublediehard** [comment]
are you a developer? do you know how Rest API works? or how JavaScript `fetch` function works?

**Comment by MzkZeeshan** [comment]
can you Invite me in slack my email address is zeeshankhanaptech@gmail.com
