### ISSUE TITLE
i cant see description of product , but only name and price

### ISSUE THREAD

**Issue by saif482** [troublediehard/magento-react-native#161]
**Describe the bug**

**Expected behavior**

**Current Behavior**
What is the current behavior?

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Navigate to...
2. Press on...
3. Scroll to...
4. See error...

**Screenshots**

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.1.0]

**Additional context**

**Comment by troublediehard** [comment]
@saif482 you forgot to fill the bug report

**Comment by troublediehard** [comment]
I'm closing this issue since you switch to the conversation on Slack
