### ISSUE TITLE
magento app does not place order

### ISSUE THREAD

**Issue by MzkZeeshan** [troublediehard/magento-react-native#17]
when i am place its say your order is sucessfully done bur then i check in my admin pannel it does not have order

**Comment by MzkZeeshan** [comment]
its my humble request for you

**Comment by troublediehard** [comment]
Did you check the response from place order request? 

p.s. don't worry I'm very tired as well, I think even more than you.

**Comment by MzkZeeshan** [comment]
why you tired

**Comment by troublediehard** [comment]
and why you?

**Comment by MzkZeeshan** [comment]
when i am place its say your order is sucessfully done bur then i check in my admin pannel  it does not have order

**Comment by MzkZeeshan** [comment]
because order is not successfully done

**Comment by troublediehard** [comment]
and what makes you tired?

**Comment by MzkZeeshan** [comment]
plz help us

**Comment by troublediehard** [comment]
I can't help you because you are not sharing information about your problem. I've asked you at least 4-5 time check fetch request-response, but you just keep saying it is not working. 

Please share some useful information so we can resolve it.

**Comment by troublediehard** [comment]
Do you understand what I'm asking you? Where did you stuck with checking response?

**Comment by troublediehard** [comment]
Also, you can join Slack workspace it would be easier to guide you how to debug your problem there.

**Comment by troublediehard** [comment]
Close issue because error details weren't provided.
