### ISSUE TITLE
Issues on running app

### ISSUE THREAD

**Issue by SuPInoWeb** [troublediehard/magento-react-native#194]
error: src/actions/RestActions.js: #<WeakSet> could not be cloned.

**Comment by dimaportenko** [comment]
https://github.com/dimaportenko/magento-react-native/issues/187

**Comment by dimaportenko** [comment]
https://github.com/dimaportenko/magento-react-native/issues/184

**Comment by SuPInoWeb** [comment]
Not working for me

**Comment by dimaportenko** [comment]
thanks for letting me know.
