### ISSUE TITLE
Problem build demo with react-native-vector-icons

### ISSUE THREAD

**Issue by italolourenco** [troublediehard/magento-react-native#29]
I have a problem build this demo:

Problem

A problem occurred evaluating project ':react-native-vector-icons'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

**Comment by troublediehard** [comment]
hey @italolourenco, I've just made commit with gradle version update. Can you try again?

**Comment by italolourenco** [comment]
Thanks @troublediehard. The build is ok now but in device return error "The development server returned response erro code: 500"

**Comment by troublediehard** [comment]
can you share screenshot?

**Comment by troublediehard** [comment]
@italolourenco you can try following solution https://github.com/troublediehard/magento-react-native/issues/16#issuecomment-441111803

**Comment by troublediehard** [comment]
closing this issue since RN version was updated
