### ISSUE TITLE
How to configure CMS block to get image slider and featured product in JSON response?

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#38]
I have created a cms block and added two category list in it, one is men sale and other is women sale, I don't know which plugin you have used to show  image carousel(slider) hence i haven't added any image slider.

When i am hitting this api
`http://13.233.82.59/magento/index.php/rest/default/V1/cmsBlock/19`

I am getting this response in JSON API
`{"id":19,"identifier":"MHP9","title":"Mobile Home Page","content":"<p>{{widget type=\"Magento\\CatalogWidget\\Block\\Product\\ProductsList\" title=\"Men Sale\" show_pager=\"0\" products_count=\"10\" template=\"Magento_CatalogWidget::product\/widget\/content\/grid.phtml\" conditions_encoded=\"a:2:[i:1;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Combine`;s:10:`aggregator`;s:3:`all`;s:5:`value`;s:1:`1`;s:9:`new_child`;s:0:``;]s:4:`1--1`;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Product`;s:9:`attribute`;s:12:`category_ids`;s:8:`operator`;s:2:`==`;s:5:`value`;s:2:`31`;]]\"}}<\/p>\r\n<p>{{widget type=\"Magento\\CatalogWidget\\Block\\Product\\ProductsList\" title=\"Women Sale\" show_pager=\"0\" products_count=\"10\" template=\"Magento_CatalogWidget::product\/widget\/content\/grid.phtml\" conditions_encoded=\"a:2:[i:1;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Combine`;s:10:`aggregator`;s:3:`all`;s:5:`value`;s:1:`1`;s:9:`new_child`;s:0:``;]s:4:`1--1`;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Product`;s:9:`attribute`;s:12:`category_ids`;s:8:`operator`;s:2:`==`;s:5:`value`;s:2:`30`;]]\"}}<\/p>","creation_time":"2019-03-26 09:54:43","update_time":"2019-03-27 07:32:13","active":true}`

This JSON response  is not in the format that you are getting in your app. Hence I am unable to show anything on Home screen.

I am attaching the link of image showing cms block from magento admin that I have created
[Image 1](https://imgur.com/NdpWmRX)
[Image 2](https://imgur.com/6sWX0Ca)

Can you tell me how to configure CMS Block to get JSON response like you are getting for home screeen.

**Comment by troublediehard** [comment]
As I can see you receive the same data as you put to the cms block, so it is working correctly. What do you want to receive on the mobile app end?

**Comment by alexakasanjeev** [comment]
I want the response that you are getting for home data

`{
  "slider": [
    {
      "title": "New Luma Yoga Collection",
      "image": "wysiwyg/home/home-main.jpg"
    },
    {
      "title": "Even more ways to mix and match",
      "image": "wysiwyg/home/home-t-shirts.png"
    },
    {
      "title": "Find conscientious, comfy clothing in our eco-friendly collection",
      "image": "wysiwyg/home/home-eco.jpg"
    }
  ],
  "featuredCategories": {
    "30": { "title": "Woman Sale"},
    "31": { "title": "Man Sale"}
  }
}`

I want like this so that I can easily extract values and display sliders and list

**Comment by troublediehard** [comment]
To get such result, you have to put it to the cms block content.
<img width="877" alt="Screen Shot 2019-04-18 at 10 52 03 AM" src="https://user-images.githubusercontent.com/6594232/56345313-1d091a00-61c8-11e9-8bab-1ea47385e1fb.png">

**Comment by alexakasanjeev** [comment]
So you mean you manually typed in this format in the editor????

**Comment by troublediehard** [comment]
yes, no magic :)

**Comment by troublediehard** [comment]
if you want to generate it automatically, you have to create Magento module which will have admin interface, will generate this output from your selection, and create custom API endpoint to get this information.

**Comment by alexakasanjeev** [comment]
Ok thanks for clarification, and how did you know image url, "wysiwg/home/home-t-shirts.png", ??

**Comment by troublediehard** [comment]
on magento side it was added from wysiwg editor
<img width="1001" alt="Screen Shot 2019-04-18 at 7 41 52 PM" src="https://user-images.githubusercontent.com/6594232/56377140-5f574900-6212-11e9-8d31-d99a1d2d2d6d.png">


on mobile app side 
```
getMediaUrl() {
    return this.storeConfig.base_media_url;
  }
```
