### ISSUE TITLE
Order screen show previous user orders, if logout and logged in from new account 

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#45]
**DESCRIPTION:** I logged it into an account, it showed the order related to that customer, now I logged out and created new account(app instance was never closed), In my order screen it showed previous user order.

**Expected behavior:**
My order screen should have been blank

But once I closed the app completely and relaunched, it showed blank screen in OrderScreen

**Comment by troublediehard** [comment]
Thanks, @alexakasanjeev. Good point, we need to clean up user-related data on log out.

**Comment by troublediehard** [comment]
fixed
