### ISSUE TITLE
Getting issue 

### ISSUE THREAD

**Issue by lavarajallu** [troublediehard/magento-react-native#5]
When i was download this app application not run android and ios 

getting like this 
![screen shot 2018-08-08 at 12 02 41 pm](https://user-images.githubusercontent.com/20550556/43820192-2a3a4780-9b03-11e8-8cdc-8dabebf95846.png)

**Comment by troublediehard** [comment]
@lavarajallu you have to follow setup process from the readme. As I can see you didn't create `magento.js` file.
