### ISSUE TITLE
Product that you are trying to add is not available

### ISSUE THREAD

**Issue by mak147** [troublediehard/magento-react-native#50]
**Describe the bug**
"Product that you are trying to add is not available" this message is not cleared when visiting other available product 

**Expected behavior**
"Product that you are trying to add is not available" this message should be cleared after page refreshed..

**Current Behavior**
"Product that you are trying to add is not available" this message not cleared when visiting available product..its stays there and cleared when add to cart button pressed..
*Screenshots**
![Screenshot_2019-05-28-00-26-49-842_com magento_mobile_app](https://user-images.githubusercontent.com/43117548/58436532-52febf80-80df-11e9-86ab-e2b3d6e2d3b7.png)

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.2.3]
 - Device: [e.g. xiaomi mi mix2]
 - OS: [e.g. miui 10]
 - Version [e.g. 10.2.0.1]

**Comment by troublediehard** [comment]
@mak147 thanks for the report, @Dtema1996 please take a look.

**Comment by mak147** [comment]
Yes perfectly working now

**Comment by troublediehard** [comment]
No actions were taken still has to be reviewed.

**Comment by mak147** [comment]
Ohh sorry i thought you fixed it.

**Comment by Dtema1996** [comment]
@troublediehard check it out, please

**Comment by troublediehard** [comment]
done
