### ISSUE TITLE
Can you add push notification in this app it would great feature for targeting cutomers

### ISSUE THREAD

**Issue by mak147** [troublediehard/magento-react-native#51]
**Is your feature request related to a problem? Please describe.**
No its not related to problem.

**Comment by troublediehard** [comment]
I can add it, but not sure if I should. To add Push Notifications with Firebase you need simply add dependencies and follow all setup instructions like here https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591. But it will increase the complexity of the initial project setup. And for people who don't need it or don't want to use Firebase, it will be a problem to remove these dependencies.

Thanks for the feedback, I'll think more about the pros and cons.

**Comment by mak147** [comment]
If its implemented it would be great feature.thanks for replay.
