### ISSUE TITLE
Need product name text overflow hidden

### ISSUE THREAD

**Issue by mak147** [troublediehard/magento-react-native#52]
Can bigger product name adjusted in one line and more text can be hidden so that it doesn't effect the product image to displaced and text will be within the product name box.thanks 

![IMG_20190528_084638](https://user-images.githubusercontent.com/43117548/58449955-4d789800-8126-11e9-967e-2e4219555ebf.jpg)

**Comment by troublediehard** [comment]
@Dtema1996 please take a look.

**Comment by Dtema1996** [comment]
@troublediehard Check it out, please

**Comment by troublediehard** [comment]
done
