### ISSUE TITLE
Can add to cart button adjusted after product gallery?

### ISSUE THREAD

**Issue by mak147** [troublediehard/magento-react-native#53]
Please adjust the add to cart button and quantity info after product image gallery in product detail page so that customer don't have to scroll down or search for add to cart button while initiating add to cart button on multiple lines short discription
![IMG_20190528_084743](https://user-images.githubusercontent.com/43117548/58450355-fffd2a80-8127-11e9-807e-a0f5cf8f3fc9.jpg)
![Screenshot_2019-05-28-08-47-08-305_com magento_mobile_app](https://user-images.githubusercontent.com/43117548/58450362-07bccf00-8128-11e9-8c78-0ae2fbaabc90.png)

**Comment by Dtema1996** [comment]
@troublediehard Check my pull request, please.

**Comment by troublediehard** [comment]
done
