### ISSUE TITLE
Cart refreshes and blanks out

### ISSUE THREAD

**Issue by sodhanii** [troublediehard/magento-react-native#56]
Hi,

For some weird reason cart resets itself when I navigate between pages. 

Store IP - http://13.127.13.193/

I can email you admin credentials. 

Let me know if you can help.

**Comment by troublediehard** [comment]
hi @sodhanii, please join slack workspace via link https://join.slack.com/t/magento-react-native/shared_invite/enQtNjE3ODY0MDUxOTQyLWU4MzViODdmMTg0NTQ5MGVjYjM1ODI4ZTgxZDJhYzFlNjMyOTI2MmZiZDIxNDBmZDJjNTQ5MGIyYmY4NzMxMzE
so we can discuss it in details

**Comment by troublediehard** [comment]
fixed in https://github.com/troublediehard/magento-react-native/commit/f2ef126219b6a4c552ed27a8ac3ccd81d7f4b54f
