### ISSUE TITLE
Update README file and add CONTRIBUTING and CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#57]
**Are there certain things to report that are not a bug or feature?**
I would like to update **README** file to look like this [README file](https://github.com/alexakasanjeev/magento_react_native/blob/develop/README.md)
I would like to add [CODE_OF_CONDUCT file](https://github.com/alexakasanjeev/magento_react_native/blob/develop/CODE_OF_CONDUCT.md) which is generic and can be added to any project
I would also like to add **CONTRIBUTING** file like [this](https://github.com/alexakasanjeev/magento_react_native/blob/develop/CONTRIBUTING.md) which will help new contributors to navigate through the process and explain them about some guideline that they need to follow .

**What's the point of this update?**
I think by providing better readme file and a contributing file, will increase the number of contribution, plus it will give them clear guideline on which things they can work on, how can they get started and help improve the project.

**Other context**
- The README changes that I am proposing aren't much that different from your already existing README file
- The CODE_OF_CONDUCT file is generic one and can be added without any change.
- The CONTRIBUTING file is pretty specific to how I organize my project and how I want to get help, if you decide to go forward, we need to make CONTRIBUTING file to reflect your style.

**Comment by troublediehard** [comment]
@alexakasanjeev 
`The README changes that I am proposing aren't much that different from your already existing README file`
Not sure what exactly you want to change.

`The CODE_OF_CONDUCT file is a generic one and can be added without any change.`
Why does the project need it? My personal feeling - I don't want to spend time to read it, so why anybody else cares? 

`The CONTRIBUTING file is pretty specific to how I organize my project and how I want to get help, if you decide to go forward, we need to make CONTRIBUTING file to reflect your style.`
Actually, I don't see there are people want to contribute. I don't want to invest time to solve a problem which not exists. 
For example, I see people have issues with project setup time to time, so invest time to create better setup guide is much more efficient from my point of view.

**Comment by alexakasanjeev** [comment]
First one: basically it was shiny label and icons(doesn't make sense over actual issue)
Second one: Agree, I didn't read myself.
Third one: I agree, I think better documentation on how to setup project has higher priority.

> I don't want to invest time to solve a problem which not exists.

Damn, you just changed my entire perspective with one line.
