### ISSUE TITLE
Better setup project instructions

### ISSUE THREAD

**Issue by troublediehard** [troublediehard/magento-react-native#58]
**Issue**  
Time to time people asks me to help with the initial project setup. 

**Solution**  
To create a detailed step by step setup guide with screenshots.

**Comment by alexakasanjeev** [comment]
Hi @troublediehard I just wrote a wiki which contains details step on how to setup the project
https://github.com/alexakasanjeev/magento_react_native/wiki/Setup

if you like it and you haven't started working on this issue, I can create a similar wiki with details instruction for you(your setup guide and my setup guide are not much different)

**Comment by troublediehard** [comment]
@alexakasanjeev ah, looks great! I'll appreciate if you can add it to my project as well.

**Comment by alexakasanjeev** [comment]
Sure, I will start working on it :)

**Comment by alexakasanjeev** [comment]
I cannot add new pages and add images as I don't have repository access, can you add me as a `collaborators` with write access(you can revoke the access after I am done editing wiki)

https://help.github.com/en/articles/adding-outside-collaborators-to-repositories-in-your-organization

**Comment by troublediehard** [comment]
I've added you as a collaborator.

**Comment by alexakasanjeev** [comment]
I am writing the instructions, in your readme instructions, you have mentioned how to add intregation token, but in your magento.sample.js file
```
export const magentoOptions = {
  url: 'http://mage2.local/',
  home_cms_block_id: '19',
  authentication: {
    login: {
      type: 'admin',
      username: 'dev',
      password: 'q1w2e3r4'
    },
    integration: {
      access_token: 'cdlodltsj3wfwd1jrx08q9nfprb5idq4'
    }
  }
};

there is option to add admin username and password, do you want me to provide instructions for that too or should I leave till integration part?
```

**Comment by troublediehard** [comment]
@alexakasanjeev I've just removed `login` part, I think it is redundant now

**Comment by alexakasanjeev** [comment]
ok, no problem

**Comment by alexakasanjeev** [comment]
Hi @troublediehard I have done creating the wiki, but i still cannot push the code, I am sending you the files, please follow the following steps

1. clone the wiki repo locally
```bash
git clone https://github.com/troublediehard/magento-react-native.wiki.git && cd magento-react-native.wiki
```
2. Delete all files except `.git` folder in it
3. Copy all the files from this [zip](https://drive.google.com/file/d/1WKIePt-KMTUw_JJNZi91oMTk8510E0Nk/view?usp=sharing) into the `magento-react-native.wiki` folder
4. Do git add
```
git add .
```
5. Do git commit
```
git commit -m "Updated wiki"
```
6. Do git push
```
git push origin master
```
7. It will ask for your github username and password(I know you know how to do git push :) )

**Comment by troublediehard** [comment]
thanks @alexakasanjeev

**Comment by alexakasanjeev** [comment]
Always happy to help :) I implore you to keep on working on this app, in making it better, so that I can learn it too and create a really good usable product.
