### ISSUE TITLE
Handle 401 http error in fetch and show error on screen

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#59]
**Is your feature request related to a problem? Please describe.**
Currently in `magento/index.js` send function doesn't handle 401 or other error HTTP code, which in turn doesn't use full potential of `try catch` block written in `RestAction.js` and there is need to manually check if there is error message from the HTTP response.

**Describe the solution you'd like**
Handle HTTP error status code like 401 and other properly in `send` function written in `magento/index.js` file. 

**Other context**
Currently the PR I have created, only in `initMagento` function in `RestAction.js` file error is handled, this need to be done in all the function written in `RestAction.js`, this blueprint need to be followed in `RestAction.js`

```javascript
export const someFunction = () => {
  return async dispatch => {
    try {
      const data = await magento.someApiEndpoint();
      dispatch({ type: SOMETHING_SUCCESS, payload: data });
    } catch (error) {
      console.log(error);
      dispatch({ type: SOMETHING_ERROR, payload: { errorMessage: error } });
    }
  };
};
```

and then these actions need to be handle in reducer like

```javascript
export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case SOMETHING_SUCCESS:
      return {
        ...state,
        data: action.payload,
      };
    case SOMETHING_ERROR:
      return {
        ...state,
        errorMessage: action.payload,
      };
    default:
      return state;
  }
};
```

and then we can access `errorMessage` from redux and show appropriate error on Screen

**Comment by troublediehard** [comment]
fixed in https://github.com/troublediehard/magento-react-native/pull/60
