### ISSUE TITLE
Remove unnecessary use of Promise in API call

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#64]
**Is your feature request related to a problem? Please describe.**
Currently API calling required three nested Promises use
1. from `fetch`, inetrnal `Promise`
```javascript
fetch(uri, { method, headers, body: JSON.stringify(data) })
        .then(response => {
            // do something
        })
        .catch(error => {
           // do something
        });
```
2. top level `Promise` return from function `send` in  `magento/index.js` file
```javascript
send(url, method, params, data, type) {
    // ...
    return new Promise((resolve, reject) => {
      console.log({ uri, method, headers, data, ...params });
      fetch(uri, { method, headers, body: JSON.stringify(data) })
        .then(response => {
          // ...
        })
        .then(responseData => {
          // ...
        })
        .catch(error => {
          // ...
        });
    });
  }
```
3. Promise written in `admin/index.js`, `customer/index.js` and `guest/index.js` file
```javascript
export default magento => {
  return {
    getStoreConfig: () => {
      return new Promise((resolve, reject) => {
        const path = '/V1/store/storeConfigs';

        magento
          .get(path, undefined, undefined, ADMIN_TYPE)
          .then(data => {
            //...
          })
          .catch(e => {
            // ...
          });
      });
    },
  };
}
```

**The third `Promise` is totally unnecessary.** We can simply return the `Promise` from 2 into the third one, in turn reducing the unnecessary memory required to create new promise and writing repeated code in `admin/index.js`, `customer/index.js` and `guest/index.js` file which is violating DRY(Do Not Repeat) Principle.

**Describe the solution you'd like**
Simply return the `Promise` return from `send` function directly in `admin/index.js` functions
```javasdcript
export default magento => {
  return {
    getStoreConfig: () => magento.get('/V1/store/storeConfigs', undefined, undefined, ADMIN_TYPE),
  };
}
```

**Additional context**
We can discuss, I would be willing to make some changes in the pull request.

**Comment by troublediehard** [comment]
fixed in https://github.com/troublediehard/magento-react-native/pull/65
