### ISSUE TITLE
Use currency API to fetch currency symbol

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#66]
**Is your feature request related to a problem? Please describe.**
Currently the currency symbol are statically defined in `src/helper/price.js` and `priceSignByCode` function is used to get currency symbol. There is a currency API `/V1/directory/currency` which returns the default currency along with currency symbol. This API should be used to append currency Symbol to the prices instead of manually providing currency.

**Describe the solution you'd like**
1. hit the API `GET /V1/directory/currency`
```json
{
    "base_currency_code": "USD",
    "base_currency_symbol": "$",
    "default_display_currency_code": "USD",
    "default_display_currency_symbol": "$",
    "available_currency_codes": [
        "USD"
    ],
    "exchange_rates": [
        {
            "currency_to": "USD",
            "rate": 1
        }
    ]
}
```
2. Save the response in `MagentoReducer`
3. Use redux to get currency symbol from the reducer
```javascript
const mapStateToProps = ({ magento }) => {
  const { default_display_currency_symbol: currency_symbol } = magento;
  return {
    currency_symbol
  };
};
```

**Additional context**
[Magento 2 API list](https://devdocs.magento.com/guides/v2.3/rest/list.html)
If you approved, I would like to work on this issue.

**Comment by troublediehard** [comment]
@alexakasanjeev sure, you can add if you like.

**Comment by alexakasanjeev** [comment]
ok, I will work on this issue.

**Comment by alexakasanjeev** [comment]
Created a pull request, please review when you will have time, and I have also commented on some changes.
