### ISSUE TITLE
Invariant Violation Error

### ISSUE THREAD

**Issue by Insha-Siddiquii** [troublediehard/magento-react-native#69]
I got the below mentioned error when application build and run. 
I am using the following versions:
magento: 2.3
react-native-cli: 2.0.1
react-native: 0.59.10
OS : windows10

IMAGE SCREENSHOT FOR ERROR REFERENCE:

![image](https://user-images.githubusercontent.com/49707515/64493505-59820300-d29a-11e9-9ea3-ffc3cbe27b5b.png)

**Comment by troublediehard** [comment]
@Insha-Siddiquii have you done https://github.com/troublediehard/magento-react-native/wiki/Setup#2-setup-new-cms-block-in-magento-admin-which-will-be-used-in-homepage ? It looks like something wrong with your homepage config.

**Comment by Insha-Siddiquii** [comment]
yeah i followed all setup guide and there was no problem in that. I inspected the problem , this was actually with react native that does not allow my store url to fetch data and initialize magento. Problem solved when i changed my store url  from http://localhost/xxxxx to http://ip-address:port/xxxx.

**Comment by troublediehard** [comment]
Happy to hear you solved it.
