### ISSUE TITLE
Categories list displayed but images and Products not displayed yet 

### ISSUE THREAD

**Issue by lavarajallu** [troublediehard/magento-react-native#7]
Hi i am followed your application  i am successfully got  the categories . But i am not get the categories images and product images as your follow application.
Especially i am not getting products 

I gave my Base URL & AccessToken

**Comment by troublediehard** [comment]
@lavarajallu can you attach screenshots?

**Comment by lavarajallu** [comment]
can you come to slack

**Comment by troublediehard** [comment]
@lavarajallu I've sent you invite to the Slack
