### ISSUE TITLE
access_token easily found in index.android.bundle

### ISSUE THREAD

**Issue by hkvega01** [troublediehard/magento-react-native#71]
if allow all resources for the access token, are there any security risks concern?

**Comment by troublediehard** [comment]
@hkvega01 you don't have to allow access to all resources

**Comment by troublediehard** [comment]
I added a note on the setup page
```
Select Resource Access to 'All' under 'API' tab (NOTE: it is only for a quick start, for production you have to allow only resources required by the app)
```

**Comment by dimaportenko** [comment]
also, here is RN docs recommendations on how to store your API keys, https://reactnative.dev/docs/security#storing-sensitive-info
