### ISSUE TITLE
Create single file for theme related content

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#75]
**Is your feature request related to a problem? Please describe.**
I would like to extract all colors, padding, margin, text size etc into single `theme.js`. This will help customize the styling of the app really straight forward, and client can modify the theme to reflect their brand style.

**Describe the solution you'd like**
1. Create [`colors.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/colors.js) to hold all colors used in app
2. Create [`spacing.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/spacing.js) that will hold standard spacing used for padding and margin.
3. Create [`typography.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/typography.js) to hold standard Text styles that can be reuse in entire app
4. Merge all `color`, `spacing`, `typography` into single [`theme.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/theme.js) which will be used by all component 

**Additional context**
I have implemented in my [magecart](https://github.com/alexakasanjeev/magento_react_native) repo, you can see it for reference.

**Comment by troublediehard** [comment]
@alexakasanjeev yes, go ahead.

**Comment by alexakasanjeev** [comment]
Hi, need some context about these two components, both of which are never used anywhere in the code.

- [Confirm](https://github.com/troublediehard/magento-react-native/blob/master/src/components/common/Confirm.js) I am guessing it's a dialog (Need context)
- [ExpandButton](https://github.com/troublediehard/magento-react-native/blob/master/src/components/common/ExpandButton.js) it's similar to Button, but don't have any background color.

Can you tell me do you have any future use of these components, also if `ExpandButton` only purpose is to show button without background, this can be easily implemented in existing `Button` component like

```javascript
<Button
    type="solid | outline | clear
``` 

where `solid` can be with background color
`outline` will have transparent  background with border around
and `clear` will be borderless and backgroundless button

**Comment by troublediehard** [comment]
@alexakasanjeev not sure how those components appeared in the project, fill free to remove them if it is not used.

**Comment by alexakasanjeev** [comment]
Hi Dmytro

I have completed most of the theme related stuff. **Do not merge the branch right now**, I will do some further testing and final changes(revert back original theme) and will create pull request.

https://github.com/troublediehard/magento-react-native/tree/feature/theme

Meanwhile for testing purpose I have chosen dark theme, as I don't have ios could you please test the branch `feature/theme` at your end in ios and check if you are satisfied with the code and implementation and that there is no breaking changes,

I have been working for 4 days straight :sleepy: 

###  It would be great help, if you would test at iOS and approve or suggest changes.
- Theme color will be change before final pull request
- Also in pull request I will mention how to use this theme correctly.

### Screenshots

![Screenshot_1570461938](https://user-images.githubusercontent.com/13250741/66326482-ae22a780-e946-11e9-9d21-fa23237da3d3.png)
![Screenshot_1570461983](https://user-images.githubusercontent.com/13250741/66326579-dad6bf00-e946-11e9-9ed6-7e901fb5b655.png)
![Screenshot_1570462248](https://user-images.githubusercontent.com/13250741/66326500-b67ae280-e946-11e9-8479-e725bca5526f.png)
![Screenshot_1570462276](https://user-images.githubusercontent.com/13250741/66326505-b7ac0f80-e946-11e9-8621-2ae5e7815260.png)
![Screenshot_1570461961](https://user-images.githubusercontent.com/13250741/66326527-c09ce100-e946-11e9-8493-58a00506a3da.png)
![Screenshot_1570461964](https://user-images.githubusercontent.com/13250741/66326530-c2ff3b00-e946-11e9-8782-8f8091867421.png)
![Screenshot_1570462032](https://user-images.githubusercontent.com/13250741/66326535-c692c200-e946-11e9-946b-6b094f6320db.png)
![Screenshot_1570462077](https://user-images.githubusercontent.com/13250741/66326542-c7c3ef00-e946-11e9-8227-46abc9092081.png)
![Screenshot_1570462199](https://user-images.githubusercontent.com/13250741/66326547-ca264900-e946-11e9-9fbe-f7318e7f7f7d.png)

**Comment by troublediehard** [comment]
hey @alexakasanjeev, 
Wow! Amazing work! I did smoke test the app on iOS and it looks really great! 
I haven't reviewed all code yet but generally looks good. 

There is no 'sans-serif' font on iOS by default, so I pushed the [fix](https://github.com/troublediehard/magento-react-native/commit/a5fb4d25e575f65559c625c94b0f30be0219b95a) for it.

You can find some default fonts per OS [here](https://github.com/react-native-training/react-native-fonts?source=post_page-----ed78b48bd45e----------------------) 

Also, I see a lot of warnings appear, so need to review it as well.

**Comment by alexakasanjeev** [comment]
Thank you for reviewing, please make sure there are no error.

Also, I converted come component into functional component and used react hook for local state.

And about warning, there were lots of component for whom prop-types were not defined, I wrote prop types for many, 

So we need to fix the type defined in prop types.

**Comment by alexakasanjeev** [comment]
Hi @troublediehard 
I have created the pull request for the theme functionality.

Also at the end of PR, I have explained how to use this new functionality correctly in the APP. Please I highly implore you to at-least read the guidelines mentioned in the PR. Otherwise it will be pointless for me to do all these changes, id you cannot incorporate in your daily workflow.

And also I have mentioned in detail comments what each property do in their respective files,
for example in `colors.js` I have mentioned where each color is supposed to be used, so if you need bigger pitcher, just read the comments in `colors.js`, `typography.js` etc
