### ISSUE TITLE
Cache images with react-native-fast-image library

### ISSUE THREAD

**Issue by troublediehard** [troublediehard/magento-react-native#78]
**Is your feature request related to a problem? Please describe.**
Images are loading from the website every time, so it causes unnecessary delays and traffic usage. 

**Describe the solution you'd like**
1. Install [react-native-fast-image](https://www.npmjs.com/package/react-native-fast-image)
2. Replace all 
```
import { Image } from 'react-native';  
<Image ...
``` 
usages in the project with 
```
import FastImage from 'react-native-fast-image';  
<FastImage ...
```

**Comment by tsturtz** [comment]
im on it

**Comment by alexakasanjeev** [comment]
Hello @tsturtz , feel free to ask question if need help

**Comment by tsturtz** [comment]
Thanks - here's the PR: #80
