### ISSUE TITLE
TextInput contentType property

### ISSUE THREAD

**Issue by troublediehard** [troublediehard/magento-react-native#85]
Add where applicable
1. iOS prop textContentType  https://facebook.github.io/react-native/docs/textinput#textcontenttype
2. Android prop autoCompleteType https://facebook.github.io/react-native/docs/textinput#autocompletetype

**Comment by JuanVqz** [comment]
Hi @troublediehard Are you refering to [textContentType](https://facebook.github.io/react-native/docs/textinput#textcontenttype)? but you are solved this because Input component has `{...props}` and cover **textContentType** prop.

example:
```javascript
// Usage
<Input
  ...
  textContentType={"emailAddress"} />

// Input component
<TextInput
  ...
  {...props} />
```

**Comment by troublediehard** [comment]
@JuanVqz thanks
