### ISSUE TITLE
Update demo gif

### ISSUE THREAD

**Issue by troublediehard** [troublediehard/magento-react-native#88]
The current demo gif is outdated. Need to update the demo gif file.

**Comment by alexakasanjeev** [comment]
I would do that,

could you please mention which screens or feature you want to show

**Comment by troublediehard** [comment]
Pretty much the same as now.

**Comment by troublediehard** [comment]
some notes how to convert video to gif with ffmpeg https://gist.github.com/dergachev/4627207

**Comment by alexakasanjeev** [comment]
Hi @troublediehard I am unable to convert video to gif thats looks good, either it is too low quality or big in size, here is the link to video - [link](https://drive.google.com/file/d/1udsvgl-jAPkadlIrNT9cccRl8059y72u/view?usp=sharing)
