### ISSUE TITLE
Support localization(i18n) in the App

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#96]
**Is your feature request related to a problem? Please describe.**
Currently strings are either hard-coded in each file , which is not good for support of localization.

**Describe the solution you'd like**
1. use `i18n-js` & `react-native-localize` package in App
2. Follow similar project structure as in [ignite-bowser](https://github.com/infinitered/ignite-bowser/tree/master/boilerplate/app/i18n) boilerplate
3. Remove all hard coded strings
4. Reference all strings from `i18n` folder

**Additional context**
I have implemented it in magecart, here is the [code](https://github.com/alexakasanjeev/magento_react_native/pull/78), do you want this feature, I could work on it.

**Comment by troublediehard** [comment]
@alexakasanjeev go ahead if you want to work on it.
