### ISSUE TITLE
Support Multi currency in App

### ISSUE THREAD

**Issue by alexakasanjeev** [troublediehard/magento-react-native#98]
**Is your feature request related to a problem? Please describe.**
Allow app to change currency, which will update the currency symbol and currency rate.

**Describe the solution you'd like**

- [x] Create a `Price` component which will replace all manually defined price in `Text` component
- [x] Show drop down to select currency in Home Screen
- [x] Update currency symbol and price rate accordingly in entire app
- [x] When placing order, show price in base currency which will be charged
- [x] In Order List Screen & Order Detail Screen use currency symbol defined by `order_currency_code` irrespective of selected currency

**Additional context**
magento 2 Admin setting to add currency - [video](https://www.youtube.com/watch?v=XxPxvMMRY9M)

If you want I would like to work on it.

**Comment by troublediehard** [comment]
@alexakasanjeev sure, go ahead.
